### ISSUE TITLE
2 Noticable Bugs from 4/4/20 Update

### ISSUE THREAD

**Issue by SC3-Gazzy-Gaming** [FredyH/Perpheads-Issues#1000]
Firstly, It won't allow me to spawn road equipment into my car as LT. I click "Yes Please" and it does not. I tried this on both armoury NPC And Desk NPC. 
Also, Armoury NPC Does not state the Seats in a car. Not huge, but an issue.

**Comment by SamuelSheppard** [comment]
Armoury NPC has been fixed.

Can not replicate the first issue.
