### ISSUE TITLE
Gearing up/down with C2/Flashbang equipped causes issues

### ISSUE THREAD

**Issue by Collier9** [FredyH/Perpheads-Issues#1002]
Gearing down from Heavy to Light whilst C2/Flash is equipped doesn't work properly. My playermodel keeps it's heavy gear but can only select light gear weaponry.

Gearing up from Light to Heavy with C2/Flash equipped gives players wearing light gear access to heavy gear weaponry.

**Comment by SamuelSheppard** [comment]
Fixed
