### ISSUE TITLE
BMW Trunk Issue

### ISSUE THREAD

**Issue by HaydenPERP** [FredyH/Perpheads-Issues#1004]
@SamuelSheppard Can this bug please be fixed then: https://streamable.com/dtlks1

_Originally posted by @HaydenPERP in https://github.com/FredyH/Perpheads-Issues/issues/998#issuecomment-610368878_

**Comment by HaydenPERP** [comment]
Recreated new issue as other one was closed. Please see video here for bug: https://streamable.com/dtlks1

**Comment by SamuelSheppard** [comment]
**Fixed in commit 6934177.**

Issue was that we dont check how much a car can hold. I have refactored the code and it now works as it should
