### ISSUE TITLE
Police Cars for Non VIPs

### ISSUE THREAD

**Issue by jimmythehamster** [FredyH/Perpheads-Issues#1015]
Seems to be bugged - cars were set to 6 according to the Book of Law. 5 officers had cars spawned yet I couldn't spawn one as a non VIP player.

**Comment by jimmythehamster** [comment]
Note that it gives you the option to spawn one but it doesnt spawn

**Comment by TinySimon** [comment]
This doesn't look possible in the code, and I can't reproduce it. What vehicle where you trying to spawn?

**Comment by jimmythehamster** [comment]
I took some ss
![20200424214705_1](https://user-images.githubusercontent.com/14095780/80260235-54ce5b80-867f-11ea-904b-11e46fcbf0b1.jpg)
![20200424214655_1](https://user-images.githubusercontent.com/14095780/80260236-5566f200-867f-11ea-9491-93e540526409.jpg)

You can see BoL says 8 vehicles are available - and PD computer says 6 officers have vehicles spawned meaning there should be 2 free slots. I was trying to spawn a TFU land rover but it's the same for any PD car. Nothing would spawn for me.
