### ISSUE TITLE
Resuppling

### ISSUE THREAD

**Issue by jimmythehamster** [FredyH/Perpheads-Issues#1017]
![image](https://user-images.githubusercontent.com/14095780/80285577-e8ef0000-871d-11ea-9c98-df46c5518eff.png)

Literally unplayable

**Comment by nutrient10** [comment]
what

**Comment by Collier9** [comment]
> what
> 
> I don't think anybody is going to understand what's going on here.

It's missing a 'y'

**Comment by AyjayMartin** [comment]
This is what happens when you get Swedish people to code @SamuelSheppard 

Fixed

**Comment by nutrient10** [comment]
I'm a bit blind

**Comment by jimmythehamster** [comment]
correct

**Comment by SamuelSheppard** [comment]
@AyjayMartin Not my code! This code has been here for a year :(

I have no "i" in my name https://i.imgur.com/RdSHWUi.png
