### ISSUE TITLE
Setting 99 or 100 HP does nothing, 98 does

### ISSUE THREAD

**Issue by Collier9** [FredyH/Perpheads-Issues#1024]
For some reason when I set my hp to 100 using !hp 100 or !hp 98, nothing happens. 98, however, will heal me.

https://i.gyazo.com/64cad61539faa7b59eb640484379d360.mp4

**Comment by TinySimon** [comment]
You were just setting the health HP of someone with "99" or "100" in their name to be 100. I'm going to make player a required parameter to solve this, but will break the "!hp 100" command, but I don't think that's the end of the world.
