### ISSUE TITLE
Trunk Bug?

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#1025]
Not even sure if this is a bug but this doesn't seem right at all, plenty of space and weight to go but crafting materials only seem to stack up to 10 yet my inventory can carry 300 in one go?

Haven't tested with any other types of items but I guess that might not matter anyway.

Reproduce by putting items into a car trunk

Image:
https://i.imgur.com/OW9pxm0.png

**Comment by Collier9** [comment]
I am pretty sure this has to do with the ITEM.MaxStack value, which is 10 for plastic and 1 for guns. This didn't work properly for a while and, I believe, was fixed recently.

You might be better off making a suggestion for the values for certain crafting materials to be increased.

**Comment by SamuelSheppard** [comment]
Not a bug
