### ISSUE TITLE
OOC + TAB issue

### ISSUE THREAD

**Issue by blobvis20** [FredyH/Perpheads-Issues#1026]
If you try to open a menu and click on a button on your tab menu you cant with the bottom 5 because the chat box is in front of it, can we please put the chatbox to the background if you hold tab? So I can finally use command through tab again for the bottom X amount of players

**Comment by TinySimon** [comment]
Duplicated here: https://perpheads.com/threads/text-box-is-in-front-of-tab-menu.43224/
