### ISSUE TITLE
SCAMBans Blacklist?

### ISSUE THREAD

**Issue by A1JK** [FredyH/Perpheads-Issues#1034]
If someone has issued a blacklist and they are unbanned the reason, date & admin will appear as

table.UnblacklistReason
table.UnblacklistDate
table.UnblacklistAdmin

I'm guessing this is cause it's not logged in any database or something? Unsure, but just wanted to report this just incase it wasn't supposed to be like this

**Comment by SamuelSheppard** [comment]
Fixed, will be live within a few days
