### ISSUE TITLE
AFK as a Job

### ISSUE THREAD

**Issue by dovjackn** [FredyH/Perpheads-Issues#1037]
So. Long story short, I saw an officer just sitting inside his vehicle for a good 20 minutes, when checking logs he has been getting his AFK Time Checker and the log specifically says **"Player demoted for AFK. Question: Unanswered"**, this happend at 15 Dec 2020 16:00:51, 15 Dec 2020 16:20:51 & 15 Dec 2020 16:40:51. The user has been in their vehicle the entire time, without even being demoted for AFK although it says he was demoted for AFK. Look up his steamid if you wish STEAM_0:0:78739387.

The latest log is me demoting him - https://i.imgur.com/OD8OB4E.png

**Comment by TinySimon** [comment]
Fixed
