### ISSUE TITLE
Sgts not appearing on Police computer

### ISSUE THREAD

**Issue by TheHitMan1** [FredyH/Perpheads-Issues#1038]
![4000_screenshots_20210103151853_1](https://user-images.githubusercontent.com/31617183/103482195-60118380-4dd7-11eb-9bf7-076d4073280e.jpg)
Sgts dont appear on the police computer and have black names in text chat

**Comment by TheHitMan1** [comment]
![Uploading 4000_screenshots_20210103152250_1.jpg…]()

**Comment by TinySimon** [comment]
Fixed
