### ISSUE TITLE
Ramming doors at city hall

### ISSUE THREAD

**Issue by jimmythehamster** [FredyH/Perpheads-Issues#246]
The doors at city hall can't be rammed open with the battering ram or c2 for some reason.

**Comment by SomoneWhoLikesTrains** [comment]
I think this has been there for ages, i could never ram or c2. This is tricky in hostage sits for ex.
Think it was intentional but should be fixed.

**Comment by LaCreepis** [comment]
This was never possible since those are public doors that only some government employees can lock or unlock (Mayor, Secret Service and IIRC Lieutenant (s))

**Comment by jimmythehamster** [comment]
It should be possible, as sneaky said it just fucks with hostage situations. It would also be nice to be able to ram the doors at the bank too.

**Comment by syl0r** [comment]
This is so you can't open doors that you shouldn't be able to open, maybe we will change it in the future.
