### ISSUE TITLE
Body ID thingy doesn't specify caliber

### ISSUE THREAD

**Issue by Xquality** [FredyH/Perpheads-Issues#454]
Right now criminals can shoot a person with a beretta m9, take the person's gun (M4A1 for example) and tell the police the criminal had the beretta m9 (therefore gaining an M4A1). 
IDEA: The ID tool should specify which caliber was used on the body (doesn't tell the gun, just the caliber). ADDITIONAL: Add a way for police to inspect weapons before confiscating - let's them see if there's a mag, how many bullets in the mag, and what caliber it uses. In the same dialog box you can press "confiscate" or "OK"
ANOTHER BUG: ID tool can identify who killed someone with a grenade. That's a bit retarded. There should be no evidence.

**Comment by jimmythehamster** [comment]
It usually tells you the gun used but it's been quite buggy as of late.

**Comment by TinySimon** [comment]
Not a bug!
