### ISSUE TITLE
Police Computer Owned Properties Section Bugged.

### ISSUE THREAD

**Issue by jimmythehamster** [FredyH/Perpheads-Issues#459]
When using the property search function to find the owner of a property I've noticed that a lot of the time people's properties do not show up in their "Owned Properties" list despite popping up as the owner from the search function and their name being on the door.

I suspect this happens to properties bought prior to when the person using the police computer joined the server. It's rather game breaking in a sense that any properties bought prior to a supervisor joining the server are essential "hidden" from the police computer so warranted suspects could theoretically hide out in these properties in the knowledge that the PD cannot find them.

**Comment by jimmythehamster** [comment]
Still happening, it's rather annoying.

**Comment by TinySimon** [comment]
fixed
