### ISSUE TITLE
Can't spend any genetic points

### ISSUE THREAD

**Issue by Ohdear942** [FredyH/Perpheads-Issues#476]
So I recently joined the server and I can't spend any genetic points at all. I have 0 points in each "talent" and nothing happens when I press the green + sign. I see the animation of the button click but I get no points at all. I made a report of it but got no help. My ability to play is very limited becauase of this so I can't really do anything. my IGN is Revoo Jenkins. I purchased VIP 20min after joining server aswell.

**Comment by Ohdear942** [comment]
I was told to make a bug report aswell.

**Comment by SteyLex** [comment]
Try to reset them at the hospital?
