### ISSUE TITLE
Fish Dupe Glitch

### ISSUE THREAD

**Issue by YaseenF** [FredyH/Perpheads-Issues#532]
When you catch a fish out of the lake using your fishing rod you get more fishes the more you click E on the fish you caught . this happened me today eariler when i was at hicktown

EDIT : i found out that you cant storage/drop/eat them 
EDIT : its only work on trout raw
EDIT : you can cook them in "Crafting" menu but the number of the bugged fish you have will stay but you can still eat the cooked raw
Bugged fish will get removed when you reconnect lel

**Comment by syl0r** [comment]
Can't seem to reproduce this
