### ISSUE TITLE
Broken radio stations

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#551]
These radio stations .pls streams no longer work and need to be replaced (If you need me to find me some DM me). Atleast that's the case for Germany.
89.3 Hip Hop
93.7 Trance
95.9 Christmas Classics (Why do we still have this xd)
100.3 Sound Tracks
101.9 House
102.1 Hard Rock
104.5 Classic Country
104.9 Reggae Kings
105.3 Smooth Jazz
105.7 Specific Radio (Danish)

**Comment by syl0r** [comment]
find some!

**Comment by LaCreepis** [comment]
Hip Hop: Hip Hop Request # 1 In Hip-Hop and RnB  http://149.56.175.167:5461/listen.pls?sid=1
Trance: Dance UK Radio http://uk2.internet-radio.com:8024/listen.pls
Sound Tracks: CINEMIX https://www.internet-radio.com/servers/tools/playlistgenerator/?u=http://149.56.23.7:20082/listen.pls?sid=1&t=.pls
House: Exit Radio UK http://uk6.internet-radio.com:8454/listen.pls
Hard Rock: MetalRock.FM CSNX-8766 http://149.56.23.7:8766/listen.pls?sid=1
Classic Country: HPR1: Traditional Classic Country from Heartland http://50.7.70.58:8708/listen.pls
Reggae Kings: UKVIBES.NET - Birmingham's No.1 Reggae Station http://uk2.internet-radio.com:8100/listen.pls
Jazz: Smooth Jazz Florida http://us1.internet-radio.com:11094/listen.pls
Since the Danish radio is dead get iLoveRadio in, always used to listen to this in GTA SAMP RP servers, German host. They don't have .pls streams, not sure if you can do it via .m3u. If it doesn't work then put in whatever you wish as I have no other suggestions.
http://www.iloveradio.de/iloveradio.m3u
http://stream01.iloveradio.de/iloveradio1.mp3
http://stream12.iloveradio.de/iloveradio1-aac.mp3

IMO get rid of Christmas Classics, it's bloody summer.

**Comment by Haydspalms** [comment]
Nearly Christmas!

**Comment by syl0r** [comment]
Hard Rock/Trance don't seem to work ingame. However, ILoveRadio works, which means we can use m3u files.

As Haydspalms said, we also need a new christmas radio, additionally 80's/90's Hits should also be swapped out, since they always play an ad when you start playing.

Could you please find some for those? Thank you crêpis.

**Comment by Haydspalms** [comment]
Just found this one, you might be interested - https://control.internet-radio.com:2199/tunein/radioxmas.pls

**Comment by syl0r** [comment]
That one works, thanks hayden

**Comment by ErmakDimon** [comment]
https://www.playradio.org/PlayRadio.m3u this is apparent;y 90s, see if it works

**Comment by LaCreepis** [comment]
Some of these may have ads
80s: http://www.radioforest.net/radio/264781.pls
Hard Rock: http://www.radioforest.net/radio/276728.pls
90s: None found as they were dead for me, find some from the RadioForest.net link like the 80s one.
Trance: Same with 90s
