### ISSUE TITLE
Being warranted while online does not give you the option to hand yourself in

### ISSUE THREAD

**Issue by magemagicc** [FredyH/Perpheads-Issues#557]
To explain it a bit further:

You kill some cops -> Get warranted by SGT+ -> Warrant is on the police computer

However when you approach the Desk NPC you do not get the option to hand yourself in, multiple times this has kind of fucked people over because they automatically assume they are not wanted as there is no option to hand themselves in. Whereas in fact the warrant is still in place on the police computer. It is fixed by reconnecting (I believe) but still fairly annoying that it occurs because you are online while a warrant is placed..

**Comment by magemagicc** [comment]
This also just occurred to us after robbing the bank (new system)

**Comment by TinySimon** [comment]
fixed
