### ISSUE TITLE
Shooting Rifle ammo for like a hour but didnt level me up on F1 or Q only on notifications

### ISSUE THREAD

**Issue by JBirksy** [FredyH/Perpheads-Issues#558]
Shooting Rifle ammo for like an hour but didn't level me up on F1 or Q only on notifications, can you just give me the levels or do you need to give me the 48 sniper ammo boxes?

**Comment by magemagicc** [comment]
are you using your own ammo or the free ammo given at the shooting range?

**Comment by JBirksy** [comment]
I'm using my own ammo

**Comment by JBirksy** [comment]
Logged on today and its went down to 48 and even when I shoot its level 48 not the 86 I got it up to after reloging and using it all to level up again, just a question will I just get the level but to 86 or do I get 40k I spent on going there and the 96 boxes of sniper ammo I used, that will be such a huge waste of time I spent on the server shooting if i get tehe sniper ammo back and not just the level :/

**Comment by LaCreepis** [comment]
I also trained some marksmanship yesterday, I'll check if that also reset for me.

**Comment by JBirksy** [comment]
I provided evidence on my RR on the forums showing I got level 86 finally in a ss and a video showing it not levelling on F1 or Q

**Comment by JBirksy** [comment]
http://plays.tv/video/59a32e363a94ba50ad/rr?from=user First minute or so shows me levelling up on the notifications then at the end you see me disconnect and then click F1 and it shows no progress, also this ss shows what level I got to after I stopped using any sniper ammo at the range (96 boxes) https://steamcommunity.com/sharedfiles/filedetails/?id=1121802907

**Comment by TinySimon** [comment]
Can't reproduce, possibly a one-time thing...
