### ISSUE TITLE
Vault jacker causes some console errors

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#559]
Not sure how this was caused but this popped up in the console during a bank robbery while the vault was still being jacked.

Crazy origin on entity [-1][class CLuaEffect]
	Origin:           [2767.794189, -15006.456055, -16391.759766]
	Angles:           [-31.122635, -65.654205, 114.211250]
	Velocity:         [0.000000, 0.000000, -655.921753]
	Angular Velocity: [-24.683714, 14.175190, -12.877027]
Defusing!
Removing!
Crazy origin on entity [-1][class CLuaEffect]
	Origin:           [2511.811035, -14992.275391, -16391.152344]
	Angles:           [28.440933, -177.989731, 156.464310]
	Velocity:         [-0.000000, 0.000000, -735.942810]
	Angular Velocity: [-1.779102, -22.056768, -2.001688]
Defusing!
Removing!

**Comment by Exnem** [comment]
It also seems to be crashing the server now.

**Comment by FredyH** [comment]
can't fix that unfortunately
