### ISSUE TITLE
Having fun in the monorail

### ISSUE THREAD

**Issue by HenkSpenk19** [FredyH/Perpheads-Issues#562]
When you go first person in the monorail you put your hands up. I never remember this was in v3.

http://i.imgur.com/wErAAdb.jpg

**Comment by Adikid** [comment]
Doesn't happen to me.

https://i.imgur.com/0nqbDJU.jpg
https://i.imgur.com/aQLOM0Z.png

Maybe reinstall addons? Ensure you have CSS content and what not?

**Comment by HenkSpenk19** [comment]
Okay will checking it

**Comment by HenkSpenk19** [comment]
Fixed
