### ISSUE TITLE
M9 with Surrpresor bug in the Storage

### ISSUE THREAD

**Issue by Palono** [FredyH/Perpheads-Issues#569]
Hey since a longer time i have a Barreta M9 in my storage i can`t get it out and getting this error:
[ERROR] gamemodes/perp/gamemode/modules/itemsystem/cl_storage.lua:22: attempt to index local 'stack' (a nil value)
  1. Retrieve - gamemodes/perp/gamemode/modules/itemsystem/cl_storage.lua:22
   2. TransferToInventory - gamemodes/perp/gamemode/modules/inventorygui/storage/storage.lua:98
    3. OnItemClicked - gamemodes/perp/gamemode/modules/inventorygui/storage/storage.lua:61
     4. unknown - gamemodes/perp/gamemode/modules/inventorygui/storage/storage.lua:377

**Comment by TinySimon** [comment]
Fixed

**Comment by LoganFinch** [comment]
Holy fuck was it an easy fix?
