### ISSUE TITLE
You can't see your own headlights/indicators

### ISSUE THREAD

**Issue by C0dyG** [FredyH/Perpheads-Issues#571]
https://www.youtube.com/watch?v=Qs7qvK47yBc&list=UUl0QVgEYnrK22g7s199oNdQ&index=3

**Comment by PHSneaky** [comment]
Sometimes cannot see headlights of others too while they are on.

**Comment by Exnem** [comment]
Fixed

**Comment by lelios1** [comment]
I still have the issue

**Comment by Exnem** [comment]
It only happens sometimes when your demo refreshes, otherwise it's fixed.
