### ISSUE TITLE
Courier + Grenades

### ISSUE THREAD

**Issue by ShadowJoey** [FredyH/Perpheads-Issues#581]
You can go courier with a grenade in your inventory.

**Comment by LaCreepis** [comment]
Same with any kind of other weaponry that you have.

**Comment by aeroperp** [comment]
Courier is a non-official government job so you can take weapons and stuff in the job, same with roadcrew.

**Comment by ShadowJoey** [comment]
![image](https://user-images.githubusercontent.com/32223872/31516583-f70b714e-af90-11e7-8a2d-988ca65bdf1c.png)

**Comment by SleepyMode** [comment]
officiakl

**Comment by FredyH** [comment]
fixed
