### ISSUE TITLE
Two issues.

### ISSUE THREAD

**Issue by MCGSCEFFAAWHETJH55555** [FredyH/Perpheads-Issues#588]
I am unsure if the courier issue is solved because someone bought a car for me, so I am unable to check if guys without cars can use the Delivery van yet.

I found a new issue as well: you get EXP from crafting grenade parts but not from the grenades themselves. Why?

**Comment by LaCreepis** [comment]
1. You should be able to claim a delivery van without having to own a car, I'm sure Fredy said this somewhere but not sure where.
2. Same reason as why you don't receive EXP for crafting the weapons together.

**Comment by MCGSCEFFAAWHETJH55555** [comment]
1. It was supposed to be fixed but it still wasn't.

2. That's a thing? I get EXP for crafting weapons together but not grenades.
