### ISSUE TITLE
Courier Baseball Bats

### ISSUE THREAD

**Issue by JDaymon** [FredyH/Perpheads-Issues#592]
You can order Baseball Bats as a Cop with the courier

**Comment by LaCreepis** [comment]
pls dont fix

**Comment by JDaymon** [comment]
@LaCreepis it got smoof to go ahead and get suspended and then suicide and gunpoint random people lol

**Comment by LaCreepis** [comment]
what a special person

**Comment by HenkSpenk19** [comment]
They also are able to have weapons on them. I was shot by a courier

### _@JDaymon dealt with it_

**Comment by jimmythehamster** [comment]
You can use this to get a bat as a medic which is fucking hilarious tbh.

**Comment by Taylor-TT** [comment]
yeah i bought like 60 of em and lost like 60k due to this

**Comment by jimmythehamster** [comment]
I don't think that's really an issue, only an idiot would do that.

**Comment by Exnem** [comment]
For the love of god, please don't fix this, it's actually fucking hilarious.
I ordered one as a cop for the lols just to prove if it was possible or not, I was speechless when I figured out that I actually could, I just used my shotgun in a raid instead and when I died I dropped it.
End of that story, never used it for anything though.


just like @LaCreepis said, please don't fix :1st_place_medal: .

**Comment by LoganFinch** [comment]
"Critical"
