### ISSUE TITLE
Storage Chest breaks after server crash restore

### ISSUE THREAD

**Issue by Askasta** [FredyH/Perpheads-Issues#598]
So after the server crashed the restoring works etc.
But after a while i found out that my storage chest dosent work anymore

https://youtu.be/3NECC3-G15E

I dont know if my items now gone but ill update this later

**Comment by Askasta** [comment]
Okey after reconnecting i found out the stuff inside dosent go lost the chest just breaks so oyu cant access it after server crash nether picking it up dosent work aswell it just becomes useless after server crash

**Comment by FredyH** [comment]
fixed
