### ISSUE TITLE
ezwallhacks

### ISSUE THREAD

**Issue by Weazelyes** [FredyH/Perpheads-Issues#603]
I somehow got this when i was at bazaar i don't know how but this is what i get (wallhacks)

https://gyazo.com/40163983cdc886e84d0d5c5f48914324

**Comment by LaCreepis** [comment]
https://puu.sh/yuRzv/5d4ea01a88.png that door model seems to be different than the standard hl2 one that we have, maybe your textures are just fucked up from some custom server or lag has caused this issue, I know that by experience that it can cause freaky things e.g. where I had my viewmodels get replaced by the worldmodels (just like TF2's vr mode https://www.youtube.com/watch?v=zIo5Ay2qiNI )
