### ISSUE TITLE
Demos

### ISSUE THREAD

**Issue by jimmythehamster** [FredyH/Perpheads-Issues#606]
In PH demos everyone is a floating head, don't know if this is fixable but it seems to be the case for everyone.

**Comment by Weazelyes** [comment]
i got the same

**Comment by TinySimon** [comment]
![image](https://user-images.githubusercontent.com/3028925/45351981-541ea980-b5af-11e8-809a-f77135f7c928.png)

`hook.Add("PostDrawTranslucentRenderables", "DrawPlayerModelESP", function()
	cam.IgnoreZ(true)
	for k,v in pairs(ents.GetAll()) do
		if((v:IsPlayer() and v:Alive()) or v:IsRagdoll()) then
			v:DrawModel()
		end
		if v:IsPlayer() then
			v:SetBodygroup(1 , 1)
		end
	end
	cam.IgnoreZ(false)
end)
`
