### ISSUE TITLE
Roadspikes are dun goofd

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#608]
![20171212150707_1](https://user-images.githubusercontent.com/14893257/33888806-6d5c41d8-df4e-11e7-8218-a5465d5f4566.jpg)
Roadspikes look like this now.
Whenever someone touches it the roadspike owner gets a notification that says "touch", some debug stuff that Fredy forgot to remove I guess.
Edit: It seems that Stephen is the culprit after all.
Edit²: The model is back but it still says 'touch' for the owner whenever someone/something touches it.

**Comment by FredyH** [comment]
fixed since long
