### ISSUE TITLE
See players in projex through wall from gas station

### ISSUE THREAD

**Issue by allen-kennedy** [FredyH/Perpheads-Issues#611]
So I was on earlier and I noticed i was able to see through the wall into projex 4 when I stood on the little wall and looked at a certain bit, I've uploaded a clip of it, the exact time of the bit is at 4:30 to 4:45 or so.
https://youtu.be/qZbiQcCuJR0

**Comment by Exnem** [comment]
Garry's mod issue as far as I know.

**Comment by allen-kennedy** [comment]
eh idk, I never seen that before.

**Comment by FredyH** [comment]
I have no idea how this happened, but it really shouldn't. Either way as Exnem pointed out, it is probably something out of our hand unfortunately :S
