### ISSUE TITLE
can't change avatar on forums

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#619]
you currently cannot change your avatar on the forums
https://perpheads.com/threads/herlp-i-cantnot-change-my-profile-picturte.30843/

**Comment by zoephix** [comment]
Having the same issue.

**Comment by LaCreepis** [comment]
I haven't kept up with any news but apparently the server changed hosts or location which breaks avatar uploads https://xenforo.com/community/threads/avatar-issue-simply-wont-change.32731/

**Comment by FredyH** [comment]
fixed, php is horrible
