### ISSUE TITLE
Critical trunk bug

### ISSUE THREAD

**Issue by Hondjeh** [FredyH/Perpheads-Issues#622]
You can get an invisible weapon on your back by putting the gun in trunk, then opening the trunk and getting in the car at the same time essentially giving you access to trunk in a car. Now if you pull out a weapon while in the car it does not show up on your back untill you expose it by pulling it out. This could obviously be very useful in a lot of situations
 
screenshots
https://steamuserimages-a.akamaihd.net/ugc/940557998140441270/77A102090545735D0FD175DF5F53B1BF8F327CDC/
https://steamuserimages-a.akamaihd.net/ugc/940557998140441416/A079DC0B97D350F7D8FA4B08565E47977289B654/

video
https://www.youtube.com/watch?v=EVs6Evv0m6I

**Comment by FredyH** [comment]
fixed

**Comment by Hondjeh** [comment]
Nope, can still do it
