### ISSUE TITLE
Console Logs/Logs giving false information on a death.

### ISSUE THREAD

**Issue by LEWIS088** [FredyH/Perpheads-Issues#630]
If you watch the following video you can see Spaceshots getting killed by a bomb blowing up.

https://youtu.be/MOs2vxj9jJs?t=11

However in the console logs it shows him being killed by a rifle.
(It also shows this in the actual logs)

*SpaceShots* | Bryon English | STEAM_0:0:93635910 | Player was killed by Citizen D3luX ジ (Colt M4A1) | Jan 29, 2018 5:29 PM
-- | -- | -- | -- | --

**Comment by TinySimon** [comment]
Fixed
