### ISSUE TITLE
Porche Cayenne Turbo

### ISSUE THREAD

**Issue by Suspine** [FredyH/Perpheads-Issues#635]
Whenever going off a speed bump at a decent speed in the Porche Cayenne the vehicle gets a tier stuck in the ground and takes an immediate sharp left always sending me into a pull in front of Bizzar instantly killing me.  This happens at every speed bump

**Comment by JDaymon** [comment]
fucking deserved when you have such an ugly car.

**Comment by JDaymon** [comment]
reopened cus im just memeing you

**Comment by Suspine** [comment]
Okay, The tire gets underground and my car just fucknig spazzes out and kills me everytime. I've been trying to sell it because it's annoying to get killed constantly but I only get 50% of it

**Comment by Weazelyes** [comment]
FUCKING DAYMON
