### ISSUE TITLE
Bug in inventory

### ISSUE THREAD

**Issue by D3luX** [FredyH/Perpheads-Issues#636]
I have this bug with beretta duplicating in my storage. I cant touch them or anything, just duplicates every time i take something out or put back. I got a silenced beretta in storage which i cant touch, and i think thats the one causing the bug.
[Picture](https://i.gyazo.com/dcca218af38d591a1bfa41659688f621.png)

**Comment by Weazelyes** [comment]
we dont help hackers

**Comment by D3luX** [comment]
Im not hacking so.. No direct proofs or anything. Sended all my requested demos and they were clean. Nothing proofs directly i have been hacking, which i havent.

**Comment by LaCreepis** [comment]
![firefox_2018-02-13_22-31-14](https://user-images.githubusercontent.com/14893257/36234279-69321a0a-11ea-11e8-9628-2950fa53f77a.png)
