### ISSUE TITLE
Sinks Bleed

### ISSUE THREAD

**Issue by EthanLennox** [FredyH/Perpheads-Issues#638]
Shooting a sink in Projex apartments (haven't tested other apartments) causes a bullet wound effect.  

http://qyndryx.co.uk/files/desk.mp4

**Comment by LaCreepis** [comment]
wtf why would you shoot it, that sink had a family

**Comment by Qyndryx** [comment]
He overcharged me for my Perphub subscription

**Comment by JDaymon** [comment]
already known

**Comment by TinySimon** [comment]
Fixed
