### ISSUE TITLE
Taurus Raging Bull description is the same as the Walther PPK

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#643]
Got confused by the caliber and the cylinder capacity first. Pls tag as fatal 
![2018-02-28_19-47-34](https://user-images.githubusercontent.com/14893257/36806424-417779e8-1cc0-11e8-94c7-4d08dfa1d95c.png)
![dllhost_2018-02-28_19-48-29](https://user-images.githubusercontent.com/14893257/36806461-5fb10af0-1cc0-11e8-92f3-04f4820c3b0b.png)

**Comment by PHSneaky** [comment]
if only they would shoot the same xd
