### ISSUE TITLE
Hats won't fuck off

### ISSUE THREAD

**Issue by Daigestive** [FredyH/Perpheads-Issues#645]
After you remove a hat from your player model. If you rejoin the server it will reappear so you have to remove the hat everytime you rejoin.
Please get rid of my black cap.

**Comment by Fintuss** [comment]
same for me, bug report been up for 20 days w/o answer.. also can't remove my gloves

**Comment by LaCreepis** [comment]
so that's why people still have the santa hat on their heads in fricking march
