### ISSUE TITLE
Being in a room full of fully equipped planter boxes fucks up your FPS everywhere even if you're not near them

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#646]
Been in a room with around 16 planter boxes full of drugs and radiators, lights and water tanks, drive to Bazaar on the highway and my FPS is still fucked around 22FPS when I get above 50 with my CPU almost anywhere in the city (Ryzen 5 1600), it's like they're still being rendered even when going out of range. Probably needs more testing but I'm not the only one affected with this issue.
EDIT: The light bulb effects seem to be the issue.

This is probably unnecesarry but I noticed less CPU usage. This was around Ragnatech, I usually floated around 40% even while nothing was going on. GPU is doing jack as usual (sometimes goes to 40% for a sec then fucks back off to 0) but this is Source that we're talking about, it works in mysterious ways.
![vlc_2018-03-10_14-19-28](https://user-images.githubusercontent.com/14893257/37242688-11e9467e-246e-11e8-88b0-e3f77b224560.png)

**Comment by FredyH** [comment]
fixed
