### ISSUE TITLE
Equipped guns don't show up on the top left corner of the inventory screen anymore

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#647]
^Title, this means that you can't take off attached equipments
EDIT: This doesn't seem to happen when you take guns out of the storage. Spawning in with guns or taking them out of a trunk seems to cause this.

**Comment by slayerduck** [comment]
This is permanent issue for plpd, it blocks plpd from switching attachments or seeing how much ammo is in the gun. So far i didn't find a workaround, putting gun in trunk and taking it out doesn't fix it either.

**Comment by FredyH** [comment]
fixed
