### ISSUE TITLE
Beretta constantly reloads in your face

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#648]
If the beretta is missing any bullets in the mag and you're not shooting it'll autoreload sometimes. It also doesn't actually shoot where it's supposed to. This can be game breaking

**Comment by Cannamonk** [comment]
I'm having the same problem. I cant function properly as a cop without my gun.
This is a critical issue.

**Comment by PuffySandvich** [comment]
Can confirm that is the fix for it. This issue can be closed.
