### ISSUE TITLE
Forum layout on mobile

### ISSUE THREAD

**Issue by magemagicc** [FredyH/Perpheads-Issues#651]
The forums' layout is a bit messed up on mobile. This was fine before hand until there was an attempt to fix something else I assume (week or two ago maybe)

![](https://puu.sh/zUHhG/cd74385f32.png)

The name is displayed nexto the icon, however the letters go down vertically and are covered by the massive steam status thing anyway. Happens on any forum post, any name.

**Comment by LaCreepis** [comment]
can we just revert to the old xenforo kthx

**Comment by LaCreepis** [comment]
Fixed since some days ago
