### ISSUE TITLE
Clothing bug

### ISSUE THREAD

**Issue by HenkSpenk19** [FredyH/Perpheads-Issues#653]
Suit buying bug; https://a.uguu.se/v4pDik42JPgl_2018-04-02_21-46-57.mp4

After I rejoined I could see it but this happend:
https://a.uguu.se/u37jGvzoHJ3W_2018-04-02_21-53-26.mp4

When I removed my hat:
https://a.uguu.se/ijREfWLI0TcT_2018-04-02_21-55-12.mp4

**Comment by Bamarin** [comment]
@HenkSpenk19 **Dead Links**
I suggest you to upload your files to a site that keeps them for longer that 24 hours

**Comment by TinySimon** [comment]
I can't reproduced this. Are you able to provide any more information?

**Comment by HenkSpenk19** [comment]
I think this is fixed
