### ISSUE TITLE
My Porsche Cayanne turbo 2012 Bug/Glitch

### ISSUE THREAD

**Issue by Kirk666** [FredyH/Perpheads-Issues#654]
Is there a way to fix this bug/glicht?  so these days it really bothers me. As you can see in the video and screen shot it happens in suburbs area and farm area. Once i died in forest area because of this glicht. And in the video you need to reverse but sometimes it not work that way. Last time an admin had to remove my car beacuse of this glicht. I will be really thankful if i can get my money back. Thank you. ( As you can see in the second picture a Road Crew worker trying to tow my car, But not working)

Evidence: https://www.youtube.com/watch?v=MEGOTI0bjss

And also some screen shot:  https://steamuserimages-a.akamaihd....890/1CC04DC30D91905D8A51A1926CB7973F212DB762/ and https://steamuserimages-a.akamaihd....188/1EFCEEE62626D4D1787EB167B4887C8B132D604E/

**Comment by TinySimon** [comment]
As we don't build our own vehicle models, there isn't much that can be done about this, besides removing the car altogether.
