### ISSUE TITLE
Can't retrieve from storage

### ISSUE THREAD

**Issue by ttjr123** [FredyH/Perpheads-Issues#659]
Me and Harry are facing a problem where we store an item (e.g. a gun) in the boot of a car and we can't get it back out even though it says the item is still in there. Respawning the car does not fix it.

I have had this issue in:
- Tesla Model S
- Range Rover 2012

**Comment by ttjr123** [comment]
A progress bar shows "retrieving", it reaches the end but the normal following "equipping weapon" progress bar does not show and the item doesn't appear in the Q wheel.

**Comment by LaCreepis** [comment]
this seems to depend on what paint type you have, what do you have on your Tesla?

**Comment by ttjr123** [comment]
Smooth metalic

**Comment by TinySimon** [comment]
fixed
