### ISSUE TITLE
HTML Error

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#660]
[HTML] :1: Unsafe JavaScript attempt to access frame with URL https://perpheads.com/youtube.php?id=VoWRSM2_DF0&volume=0&time=968 from frame with URL https://www.youtube.com/embed/VoWRSM2_DF0?controls=0&enablejsapi=1&origin=https%3A%2F%2Fperpheads.com&widgetid=1. Domains, protocols and ports must match.

**Comment by TinySimon** [comment]
fixed
