### ISSUE TITLE
Car paint using wrong sheen

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#665]
I got my car painted smooth metallic green, and this is what happened.

[https://puu.sh/AyPxx/3b444a0733.jpg](url)

It's supposed to be [https://steamuserimages-a.akamaihd.net/ugc/929311364902331419/F7B24D6F8A8AD64B74355BBCE1878B6B17AEDF0D/](url)

**Comment by TinySimon** [comment]
This just looks like lighting differences...
