### ISSUE TITLE
Dying while holding any item with your fists lets it float frozen in the air until you pick it up again with your fists

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#668]
Has been an issue for a while but never thought it would impact someone directly and result someones death because of it, here's a vid of it https://plays.tv/video/5b24301f8ef06f8ccf/welp-

**Comment by LaCreepis** [comment]
This also happens when you handcuff someone, 2lazy2edit

**Comment by TinySimon** [comment]
Fixed
