### ISSUE TITLE
Police Barricades

### ISSUE THREAD

**Issue by JaniceMcG** [FredyH/Perpheads-Issues#674]
If you buy any of the police barricades and put them into storage you are unable to retrieve them as It says "You can't put government items into storage"

**Comment by TinySimon** [comment]
I can't reproduce this. Any more information?

**Comment by JaniceMcG** [comment]
Not really, It just says the message when I try to remove them. I was speaking to someone and apparently, it is due to a staff member sending the barricades to storage when I was an officer.

**Comment by TinySimon** [comment]
Thanks, it looks to be the staff "Send to storage" command

**Comment by TinySimon** [comment]
You shouldn't be able to put them into storage anymore
