### ISSUE TITLE
Candy Metallic isnt the same as the preview 

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#678]
https://perpheads.com/threads/car-dealer-scammed-me-160-000.33980/

Candy Metallic has been broken since the multicore update, it basically looks like someone bleached the color and polished it which doesn't look very good and is a big waste of money.

**Comment by PuffySandvich** [comment]
The name of this is wrong, it's smooth metallic, not candy metallic.

**Comment by TinySimon** [comment]
Fixed
