### ISSUE TITLE
Crafting Level seems to be bugged

### ISSUE THREAD

**Issue by MaggerMags** [FredyH/Perpheads-Issues#680]
I have been crafting over the last 3 days, and I earned experience before (As im lvl 5 atm) But when I started crafting 3 days ago, nothing happend. I do have a video of the bug https://youtu.be/4fIdUxhIrEY 
This showcases me crafting ammo, and nothings happends. This is the same with furniture, drugs, weapons and magazines. I have tried to craft in larger quataties as 20 pistol ammo, but still only firearms rise.

**Comment by MaggerMags** [comment]
That is exactly the problem, as I have reported it in game, and it seems to be only me that has this problem (From asking in /help and /ooc) Thats why I was recommended to ask in here. I would also like to know if I can get the levels in another way, as I have crafted the amount to reach at least lvl 7, as I can see how much your lvl increases in that video.

**Comment by TinySimon** [comment]
Your crafting level has no reached level 7?

**Comment by MaggerMags** [comment]
Can I have my level increased in another way? It's holding me back from playing atm.
