### ISSUE TITLE
Bonemerging Errors

### ISSUE THREAD

**Issue by JaniceMcG** [FredyH/Perpheads-Issues#682]
after playing on the server for a few hours I will randomly get this error where everyone's clothes disappear and there is just floating heads also things like the Police computer and Inventory break completely.

I don't currently have images but I can try to get some next time it happens.

**Comment by jimmythehamster** [comment]
Try deleting your download/downloads folder, there's possibly something from another server you've downloaded causing errors.

**Comment by JaniceMcG** [comment]
I believe this may be fixed already. It hasn’t happened to me for a while now
