### ISSUE TITLE
911 Calls

### ISSUE THREAD

**Issue by JaniceMcG** [FredyH/Perpheads-Issues#683]
When I go dispatch, If someone calls 911 I am unable to pick it up and it starts to spam script errors.

[ERROR] gamemodes/perp/gamemode/modules/smartphone/gui/callapp.lua:60: bad argument #1 to 'upper' (string expected, got no value)
  1. upper - [C]:-1
   2. unknown - gamemodes/perp/gamemode/modules/smartphone/gui/callapp.lua:60
    3. PaintManual - [C]:-1
     4. unknown - gamemodes/perp/gamemode/modules/smartphone/gui/smartphone.lua:276

**Comment by TinySimon** [comment]
Unable to pickup as dispatcher should be fixed

Other error is due to not having a key bound to hanging up the phone. It'll be worth fixing that one too.

**Comment by TinySimon** [comment]
fixed
