### ISSUE TITLE
SR-25 Doesn't fit in Tesla trunk anymore

### ISSUE THREAD

**Issue by SteyLex** [FredyH/Perpheads-Issues#687]
SR-25 Doesn't fit in Tesla trunk anymore even though it's only 9.1KG and the trunk can hold 100KG. And when it did fit you were able to only put the SR-25 in meaning you had 90K left but you were not allowed to put more items in it.

**Comment by TinySimon** [comment]
I can't reproduce this. Are you able to provide some screenshots?
