### ISSUE TITLE
Crouching

### ISSUE THREAD

**Issue by MangoEvo** [FredyH/Perpheads-Issues#690]
Sometimes players look like they're crouching when they're actually not. You can't jump on their heads. It's not client-side as multiple other people can see the same thing when it happens.

**Comment by TinySimon** [comment]
Do you know how to reproduce this?

**Comment by HenkSpenk19** [comment]
Crouch jump in a chair fx in the pd. 
https://i.imgur.com/3bcFlOk.jpg

**Comment by TinySimon** [comment]
fixed (kind off)
