### ISSUE TITLE
Repair skill will take me a year to do

### ISSUE THREAD

**Issue by LoganFinch** [FredyH/Perpheads-Issues#691]
I fixed alot of cars yet am only 6/100, it will honestly take so long, plz nerf

**Comment by LaCreepis** [comment]
You actually gained skill levels for it? since when is this fixed tf, I thought this skill was for the old gun durability mechanic there was and not for cars where you could fix your guns

**Comment by LoganFinch** [comment]
Tiny fixed it like 10 hours ago, its closed now, but its aids, after like 20 cars fully fixing them am level 6, and it takes longer the higher the level

**Comment by TinySimon** [comment]
Not a bug
