### ISSUE TITLE
Beretta m9 bug

### ISSUE THREAD

**Issue by LoganFinch** [FredyH/Perpheads-Issues#701]
All of them you can not pick up, nor do they give a error, you can get more of the guns when you place items into storage, E.G dropping 100 cocaine into the storage produced 100 guns that you can not pick up

Main issue with this bug is it is laggy putting items into storage

This bug came into place after the gun update/marksmen I think

https://steamcommunity.com/sharedfiles/filedetails/?id=1502566914

(They are from Academy server btw)

**Comment by TinySimon** [comment]
Duplicate #569

**Comment by TinySimon** [comment]
Fixed
