### ISSUE TITLE
game randomly alt tabs

### ISSUE THREAD

**Issue by ICEKILLER99** [FredyH/Perpheads-Issues#704]
i was told to make a bug report as a lot of people have this issue aswell and there is no fix for it,its very annoying pls fix

**Comment by TinySimon** [comment]
Do you play windowed mode?

How often does it happen?

**Comment by ICEKILLER99** [comment]
Im on stretched and it happens like every 2-5 minutes

**Comment by ICEKILLER99** [comment]
it started when i changed to stretched

**Comment by TinySimon** [comment]
What do you mean by stretched?
