### ISSUE TITLE
Automatically respawn every time i die to cars.

### ISSUE THREAD

**Issue by FarmerFielding** [FredyH/Perpheads-Issues#706]
This is only regarding cars, all other deaths is as normal.

I've been killed 3 times by vehicle at 09/08/18, and all times this happened i instantly respawned after the so-called red-screen appeared. It happened just as if you get killed by the sea monster.

Video evidence from one incident.

https://plays.tv/video/5b92ffe19366718194/bug-report-third-time-it-happened-

**Comment by TinySimon** [comment]
Fixed
