### ISSUE TITLE
Radio Bug

### ISSUE THREAD

**Issue by jimmythehamster** [FredyH/Perpheads-Issues#711]
When going on duty as police/medic/firefighter/secret service there is a bug where you'll continually hear a buzzing sound as if someone has a hot mic, however in reality nobody is transmitting. Can be fixed by asking the person who the game says is transmitting to speak in radio, however if the person does not then you will continually hear the sounds until you go off duty. Going off duty and back on does not fix it.

**Comment by TinySimon** [comment]
Do you know how to replicate this?

**Comment by JaniceMcG** [comment]
I believe this occurs if you go on duty while they’re speaking or just as they finish. Still registering they’re speaking

**Comment by LaCreepis** [comment]
please just get rid of it entirely, this suggestion was accepted https://perpheads.com/threads/getting-rid-of-radio-hiss-server-side.27021/

**Comment by TinySimon** [comment]
Fixed
