### ISSUE TITLE
Swimming

### ISSUE THREAD

**Issue by ShadowJoey** [FredyH/Perpheads-Issues#713]
At higher swimming levels, the increased velocity drastically increases the ability to turn. I must slam my mouse down 4 times across the mat to do a 180. Maybe whilst increasing velocity, also increase turning sensitivity.

**Comment by TinySimon** [comment]
This is due to the engine. There is no reliable way to change it without risking permanent sensitivity changes.

**Comment by TinySimon** [comment]
I have adjusted the underwater speed slightly though.
