### ISSUE TITLE
Bank Loggs are Broken

### ISSUE THREAD

**Issue by Daigestive** [FredyH/Perpheads-Issues#714]
At around 7PM, NoHax sent me 79k from 2677580 to 8199510
I had no log of it and he did:
Him: https://gyazo.com/44787cddcea4550b30e219bd249f5760
Me: https://steamcommunity.com/sharedfiles/filedetails/?id=1514735595

**Comment by TinySimon** [comment]
Not sure how to replicate, but I have fixed one scenario where this would fail
