### ISSUE TITLE
Game Breaking Lua Errors As TFU

### ISSUE THREAD

**Issue by R-Flexx** [FredyH/Perpheads-Issues#724]
**Lua Errors as TFU at random times.**

**Cause :** Unknown , can happen at random times. It once happened as soon as another tfu officer took a taser out and shot it i think.

**Issues**
-Unable to look at the police computer database.
-PlayerModels not showing
-Script Errors

Sadly i didnt take a screenshot of the Original Script Error which caused the chained reaction

https://steamcommunity.com/sharedfiles/filedetails/?id=1522413770
https://steamcommunity.com/sharedfiles/filedetails/?id=1522413848
https://steamcommunity.com/sharedfiles/filedetails/?id=1522413896

**Comment by TinySimon** [comment]
Duplicate of #682
