### ISSUE TITLE
New Seating System bug

### ISSUE THREAD

**Issue by A1LARSEN** [FredyH/Perpheads-Issues#727]
Well tonight I cuffed a suspect and they went to run to jump in my SWAT Van, however they somehow got into the driver seat, and making them be able to drive it, and which fucked me over a lot and tried to kill me. So I mean, this kinda needs to be fixed ASAP cause anyone can basically steal cop cars then if they're cuffed.

**Comment by jimmythehamster** [comment]
that's funny as fuck

**Comment by A1LARSEN** [comment]
@jimmythehamster Had to shoot up some guy yesterday for him taking the SWAT Van and attempting to run down me and another officer and wasn't stopping for shite.

**Comment by Nutella7** [comment]
Not gonna be easy shooting an armoured swat van unless u have some high caliber weapons eks dee

**Comment by TinySimon** [comment]
Fixed
