### ISSUE TITLE
Crippled

### ISSUE THREAD

**Issue by hondjo** [FredyH/Perpheads-Issues#729]
Being crippled is not only annoying and MOSTLY a downgrade to regular health status, it can actually give positive effects when for example swimming, cuffed or right after tasing as it doesnt drain stamina. this makes it so you can not be slowed down by stamina. Example, an alt running person in cuffs can only run for about 15 seconds before having to regen again. In cuffs it does not drain and the person can run around all they want which seems counter-intuitive. Other movement impairing effects like eating ore poses are nullified.

minor but still nice to fix nonetheless

**Comment by jimmythehamster** [comment]
If we're listing ways to get around walking speed restrictions, holding ALT+CTRL allows you to drag bodies at 900mph.

**Comment by TinySimon** [comment]
fixed
