### ISSUE TITLE
NLR timer shows the wrong time remaining

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#734]
This one has been here for ages, since TinySlayer loves fixing these it's good to get rid of this too.

When you respawn the NLR timer says "4 minutes" instead of the "5 minutes" which is listed in the rules. There is also a phase where it's at 1 minute and then counts down from 60 seconds to 0 seconds which is obviously wrong.

**Comment by LoganFinch** [comment]
Oh fuck please fix this gives me pseudopseudohypoparathyroidism

**Comment by TinySimon** [comment]
done
