### ISSUE TITLE
invisible mp5k

### ISSUE THREAD

**Issue by Ardomaxi** [FredyH/Perpheads-Issues#736]
the mp5k's world model is broken, it consists of the mp5's stock and a mag coming out of it, i removed and uninstalled all PERP content, but it's still broken, any ideas?

Cheers!

**Comment by Daigestive** [comment]
Fine for me. Do yeah have any other addons? try deleting them all.

**Comment by Ardomaxi** [comment]
https://steamcommunity.com/id/dayzscreen/screenshots/
on the bottom right above the revolver, that weird looking gun

**Comment by TinySimon** [comment]
You probably have another file getting in the way. Look at deleteting your models folder and external add-ons.
