### ISSUE TITLE
fog in the gunrange

### ISSUE THREAD

**Issue by TinySimon** [FredyH/Perpheads-Issues#741]
just turn it off

**Comment by LaCreepis** [comment]
LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL ![c3f1788bd080ed4f9e69de6fa60809bd](https://user-images.githubusercontent.com/14893257/46887901-42a31880-ce5f-11e8-9ed0-c6f811209f31.PNG)

**Comment by LoganFinch** [comment]
Wait what?

**Comment by LaCreepis** [comment]
it's a note to himself

**Comment by LoganFinch** [comment]
Pmsl ok

**Comment by orzel1244** [comment]
I've waste a lot of money by buying 5k ticket for sniper range, then realised it's fog

**Comment by TinySimon** [comment]
done
