### ISSUE TITLE
Employees Tab

### ISSUE THREAD

**Issue by SGTMaas** [FredyH/Perpheads-Issues#752]
When I was demoting someone from their role as a Medic, I had encountered a lua error that most people seem to get when they play for too long, however I am able to see their bodies, guns on their back and including their head aswell, this is definilty similar but usually just the lua error when I demoted someone. 

[ERROR] gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37: Tried to use a NULL entity!
1. SetMoveType - [C]:-1
2. Reattach - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37
3. unknown - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:65

**Comment by JaniceMcG** [comment]
Tried this again and no errors, Demoted a firefighter and was fine then was demoted by A1L and was fine. May have been something else causing this
