### ISSUE TITLE
Roadcrew vehicles can drive underwater & can't drown as a driver

### ISSUE THREAD

**Issue by Aero56** [FredyH/Perpheads-Issues#755]
Somehow got in the sea with a roadcrew vehicle, could still drive the vehicle on the bottom of the sea and wasn't drowning. Passengers do drown.

**Comment by LaCreepis** [comment]
police department finally got a submarine division

**Comment by JaniceMcG** [comment]
https://gyazo.com/b0e4ab88534d78c9e76ce7f4480ccaf8

**Comment by Aero56** [comment]
thx janice

**Comment by TinySimon** [comment]
Drowning now works.
Driving requires a change in model, engine or some serious ground up code rewriting. It shouldn't be an issue now though as they drown.
