### ISSUE TITLE
Ticket reason was shortened in the police computer

### ISSUE THREAD

**Issue by nickjedl** [FredyH/Perpheads-Issues#767]
https://i.imgur.com/pTFwYjY.png

For some reason the ticket reason is shortened while the jail reason isn't.

**Comment by Aero56** [comment]
I have noticed that before, when you copy a text from a note on your phone or ticket/jail reason the last letters aren't copied, so when you paste it the last letters will be missing.

**Comment by TinySimon** [comment]
As Aero has said, this looks to be a issue with copying. Unable to replicate this or see how it is possible in the code.
