### ISSUE TITLE
being able to pick police barricades as a civ after carsh

### ISSUE THREAD

**Issue by sasr22** [FredyH/Perpheads-Issues#771]
While I was playing as ma cop I placed couple of barricades to block off an area, suddenly my game crashed and I had to rejoin. When I rejoined my props where still there and I was able to pick them up and place them back down. 

![20181117185717_1](https://user-images.githubusercontent.com/15050049/48663919-c6c06f80-ea9f-11e8-8f29-3fbf62c52871.jpg)

can upload a video too if needed

**Comment by TinySimon** [comment]
Fixed
