### ISSUE TITLE
Fake Burglar Alarms

### ISSUE THREAD

**Issue by MangoEvo** [FredyH/Perpheads-Issues#772]
If you type [Burglar Alarm] at the start of your 911 message when there's a dispatcher on duty, it will show as an actual burglar alarm to the dispatcher and will not say the fake 911 caller's phone number.

https://i.gyazo.com/139e6bc8f0b8420b944056d4dcbe12fa.png

**Comment by MangoEvo** [comment]
It also does it with other things like life alerts as well, I sent a fake message replica in and it changed the title to Life Alert by Jay Rothwell

https://i.gyazo.com/2d7de600a0437bf7fc4b061410089936.png

**Comment by LaCreepis** [comment]
that's brilliant

**Comment by TinySimon** [comment]
Fixed
