### ISSUE TITLE
Chairs being weird

### ISSUE THREAD

**Issue by lelios1** [FredyH/Perpheads-Issues#773]
You can move the entity that you sit down on away from the actual chair that it is linked to. Sometimes it works, sometimes it doesn't, but from what I could see, you can almost always get it working if you drop the chair from an altitude. Sometimes the physgun won't recognize(?) the chair as a movable prop and you won't be able to move it which is kind of annoying.

https://youtu.be/RVhsY1giSmE
Not sure if it works for everyone or just for the powered physgun.

**Comment by LaCreepis** [comment]
This only works for the moderator physgun.
