### ISSUE TITLE
Remote bomb glitch with all GOV Jobs

### ISSUE THREAD

**Issue by eclipsebas** [FredyH/Perpheads-Issues#775]
Drop remote bomb as prop then pick it up after you change job.
[https://www.youtube.com/watch?v=W-ZlO12o6g4&feature=youtu.be&ab_channel=Phantom&ab_channel=Phantom](url)

**Comment by TinySimon** [comment]
Solutions:
- Prevent players picking up bombs when in a job. Easy code, may result in left over bombs.
- Prevent players joining jobs with bombs out. More effort to code, may be a problem if the person has died.

**Comment by TinySimon** [comment]
Fixed
