### ISSUE TITLE
Fireworks

### ISSUE THREAD

**Issue by JaniceMcG** [FredyH/Perpheads-Issues#777]
I tried to launch a Small Firework outback of my bazaar shop and when it launched and was set to explode it threw an error.

> 
[ERROR] gamemodes/perp/gamemode/modules/fireworks/cl_fireworks.lua:21: attempt to call method 'SetMaterialIndex' (a nil value)
  1. CreateEffectData - gamemodes/perp/gamemode/modules/fireworks/cl_fireworks.lua:21
   2. CreateFireworksEffect - gamemodes/perp/gamemode/modules/fireworks/cl_fireworks.lua:26
    3. func - gamemodes/perp/gamemode/modules/fireworks/cl_fireworks.lua:134
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by TinySimon** [comment]
Apparently related to 64 bit - Needs more investigation.

**Comment by TinySimon** [comment]
Fixed (ish)
