### ISSUE TITLE
"Quick-aiming"

### ISSUE THREAD

**Issue by MrWinky** [FredyH/Perpheads-Issues#782]
The second you press right click, not even before the animation of you holding your sights up completes you gain the accuracy advantage of having your sights down. I've seen some top players take advantage of this and "quick-aim" their enemies and it's annoying. They can be completely unprepared, take advantage of this bug and get out unscathed. When testing with it, I found that it affects all guns, but works best with pistols.

The best way to approach this is to add a short delay to when you get the accuracy advantage after you first start holding right click.

**Comment by TinySimon** [comment]
Fixed
