### ISSUE TITLE
Drivers take more damage than passengers

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#783]
Seems a bit weird to me why the driver of a vehicle takes more damage than the passengers (probably to avoid killing passengers first instead of the driver if he's evading?). Either way this doesnt seem right so it would be best to fix this unless it's possible to add individual hitboxes for all people inside.

**Comment by TinySimon** [comment]
Previously, they didn't actually take damage at all when being shot. They now take some amount of damage, but slightly less than the driver as it is their fault.
