### ISSUE TITLE
New dragging update

### ISSUE THREAD

**Issue by ShadowJoey** [FredyH/Perpheads-Issues#784]
When players are first revived, dragging them sometimes completely fails.
https://files.perpheads.com/hwRHffTP6WvBYfSH.mp4

Will test more but this happened twice whilst he was still blurry.

**Comment by LoganFinch** [comment]
Looks like he was lagging his tits off

**Comment by LaCreepis** [comment]
Connection problem by the client. Big one.

**Comment by ShadowJoey** [comment]
Nah, he confirmed he wasn't.

**Comment by TinySimon** [comment]
Can't replicate
