### ISSUE TITLE
PD radio completely fucked

### ISSUE THREAD

**Issue by MangoEvo** [FredyH/Perpheads-Issues#785]
[ERROR] gamemodes/perp/gamemode/modules/chatsystem/cl_chat.lua:246: attempt to index a nil value
  1. func - gamemodes/perp/gamemode/modules/chatsystem/cl_chat.lua:246
   2. unknown - lua/includes/extensions/net.lua:32

That's the message when anyone tries to use /radio, /gov and cannot be seen by anyone. Everyone is using RC chat to communicate apparently.

**Comment by TinySimon** [comment]
Fixed ages ago, just needs a code refresh
