### ISSUE TITLE
Remove the fireworks from the Gun Game event

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#786]
I'm sure all the fireworks that spawn whenever someone dies in the Gun Game event create a bunch of lag (ping+FPS) so it's best to remove it entirely, it's not very helpful either IMO.

It was pretty much like this for the whole event https://gfycat.com/PeskySimpleEarthworm

**Comment by LoganFinch** [comment]
Suggestion, will making them small fireworks from large fireworks make it better in anyway?

**Comment by TinySimon** [comment]
Done
