### ISSUE TITLE
Camera bug

### ISSUE THREAD

**Issue by Nutella7** [FredyH/Perpheads-Issues#789]
After the new CCTV camera update where it TPs people down from on top of cameras, this can be used to get inside hidden rooms in hospital (get on roof with a van/ambulance and stand on top of where there cameras are and it would TP you down as if you were standing on top of it)
While not major as not many people would go on hospital roof and have this happen to them, it is still an issue

To reproduce just walk around above the CCTV cameras at hospital and it will TP you

**Comment by TinySimon** [comment]
Fixed
