### ISSUE TITLE
Forum comments are generally broken and screw with quick-reply.

### ISSUE THREAD

**Issue by PHSneaky** [FredyH/Perpheads-Issues#790]
https://i.imgur.com/QfvqHem.png
^^ is what it looks like when 2 people commented on a thread. looks a bit weird . It's confusing when you want to quickly reply to another comment since it'd be a hell to search. new comment system is also very laggy and glitchy on mobile, will describe that later

**Comment by TinySimon** [comment]
Third party plugin, not much we can do
