### ISSUE TITLE
Guns disappearing on carcrash

### ISSUE THREAD

**Issue by Sorleee** [FredyH/Perpheads-Issues#792]
Just had this happen to me with an MP5K with a suppressor & red dot, apparently the same happened to Dom yesterday and he hasn't got his gun upon relogging. Wasn't confiscated and wasn't taken by anyone else.

**Comment by LaCreepis** [comment]
Probably falls under the map/ground, had that happen before with my Admin TV where it just despawned and never went back into my storage.

**Comment by Sorleee** [comment]
Yeah, bit weird tbh

**Comment by TinySimon** [comment]
Fixed
