### ISSUE TITLE
Walther P99 Crafting Requirement

### ISSUE THREAD

**Issue by NightL0ck** [FredyH/Perpheads-Issues#793]
It says in the main menu that the needed firearms level is 30, whereas a firearms level of 34 is actually needed. Not critical or anything, but may want to be looked at at some point. I've posted some pictures below to better explain what I mean as well
![walther crafting bug1](https://user-images.githubusercontent.com/46087824/50384734-11e62780-06c9-11e9-9e1c-9cadfa6aa3e8.jpg)
![walther crafting bug](https://user-images.githubusercontent.com/46087824/50384738-1579ae80-06c9-11e9-8141-79e7ac5acd37.jpg)

**Comment by TinySimon** [comment]
This is due to the components requiring level 34.

**Comment by TinySimon** [comment]
fixed
