### ISSUE TITLE
Putting items into trunks

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#795]
When trunk slots are for example 4/4 and theres still lots of weight left it says this item does not fit into the trunk even though there is space, you have to free up a slot to stack things and it gets really annoying sometimes having to drop like 3 guns on the floor just to put 1 in

**Comment by TinySimon** [comment]
This weirdly is actually working as intended, and the the code that overstacks them is bugged.

Requires more investigation into an balanced solution.

**Comment by TinySimon** [comment]
Fixed
