### ISSUE TITLE
Baseball bats as a government employee

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#796]
Yes, you can't order a bat while a government employee but you can order one when not on duty and then go on duty and collect the bat, maybe have it give you a full refund or send the bats to your storage instead of picking them up whilst on duty.

**Comment by MangoEvo** [comment]
Should be easily fixed by not allowing them to pick up contraband packages whilst on duty.

**Comment by TinySimon** [comment]
Fixed
