### ISSUE TITLE
Luger

### ISSUE THREAD

**Issue by lelios1** [FredyH/Perpheads-Issues#797]
After you reload and aim down the sights its like this https://steamuserimages-a.akamaihd.net/ugc/964234234320213940/8E2D50639F63E46352A941376645A2E9E73961D2/ when it should be like this https://steamuserimages-a.akamaihd.net/ugc/964234234320211616/B79881A6E89E6A459E6A45150E8B1692D33D1C00/
This is fixed after you shoot.

**Comment by TinySimon** [comment]
This is due to corrupted content files and should be fixed after a complete content re installation.
