### ISSUE TITLE
Firefighters can't get bandages from the vendor.

### ISSUE THREAD

**Issue by MangoJuicePerp** [FredyH/Perpheads-Issues#799]
Simple enough. Become a firefighter, go to the NPC at the Police Deparment and he's very mean so you just say that you're John Fisher, an FBI agent, and leave without any bandages. Trouble is, who's healing the firefighters if they can't heal themselves?

**Comment by TinySimon** [comment]
Not really a bug, use the forums for feature changes: https://perpheads.com/forums/ideas-suggestions.20/
