### ISSUE TITLE
No ammo in mag even though there is?

### ISSUE THREAD

**Issue by JoeDiamond10** [FredyH/Perpheads-Issues#800]
https://youtu.be/uWTF05ZRYyc

The video really speaks for itself. For some reason, I couldn't shoot even though I clearly had a full mag. Once I reloaded, it decided to take all the ammo out of the mag. This has happened a couple times in the past couple days, and I finally got it on video. Yesterday, for some reason I even lost the magazine item from my inventory.

**Comment by TinySimon** [comment]
The issue of being able to switch weapon too early has previously been fixed and this ticket contains no information on how to reproduce this issue.
