### ISSUE TITLE
Shop Signs Reflection

### ISSUE THREAD

**Issue by TheHitMan1** [FredyH/Perpheads-Issues#802]
https://www.youtube.com/watch?v=Ki61-wuEt5k&feature=youtu.be When I turn my torch on the signs display the Word Belmont followed by some numbers, not sure it's client side or server side.

**Comment by LaCreepis** [comment]
It's for everyone. I've been playing with flashlights disabled for an eternity so I forgot about this issue in the first place.

**Comment by TinySimon** [comment]
This can't really be fixed without creating a new model. The flashlight hiding the overlay is a gmod issue.

**Comment by TinySimon** [comment]
Fixed
