### ISSUE TITLE
Bobby pin sound error

### ISSUE THREAD

**Issue by mage1123** [FredyH/Perpheads-Issues#803]
Anytime somebody uses a bobby pin anywhere on the map the following error occurs:

![img](https://puu.sh/COxSE/62648d88b4.png)
CSoundEmitterSystemBase::GetParametersForSound: No such sound Pin_Fiddle

Even though there is still a sound for when the pin "fiddles" with the door. So maybe there is a duplication of sound initialization or something? 

While it might not seem "game breaking", this can be abused by people to assume if somebody is, for example, jail breaking someone from PD while they are putting a suspect in because the error will show up in their console and they will know someone on the map is using a bobby pin.

**Comment by TinySimon** [comment]
Doesn't happen on the current content pack. Have you tried cleaning up your content to see if this still happens?

**Comment by mage1123** [comment]
Only occurs when outside of range of pin sound apparently. So you may need another person to test this with.

I'll try reinstalling my content and see if it still happens though.

**Comment by mage1123** [comment]
No longer happens after reinstalling content.
