### ISSUE TITLE
It appears that rain dancing is back

### ISSUE THREAD

**Issue by mage1123** [FredyH/Perpheads-Issues#807]
I hope this was unintended and thus a bug. Aiming down sights while running now makes you faster than when you don't aim down... the complete opposite of what is intended.

Dying to stuff like this just reminded me how anti-fun rain dancing was, please fix :(

https://gyazo.com/db81b8969d6dfb7804186c0208093c66

**Comment by NoHax** [comment]
+support!!!!!!!!!

**Comment by TinySimon** [comment]
Fixed
