### ISSUE TITLE
Meth yield bugged?

### ISSUE THREAD

**Issue by mage1123** [FredyH/Perpheads-Issues#810]
After today's update in the morning there appears to be a weird pattern occuring when doing pure meth. The yield is static at either 35, or 85, this was tested 4 times by peemnaja and he found that he either gets 35 or 85 and no other yield when doing pure meth. I'm assuming this is a bug?

![](https://steamuserimages-a.akamaihd.net/ugc/957483070088797927/BDFB2E947E9208C4E40CF2BFF07A4993C5C36FBD/)
![](https://steamuserimages-a.akamaihd.net/ugc/957483070088799938/F1CFA7EE857FEEE4C6405E0906BD8172D0F70B3C/)
![](https://steamuserimages-a.akamaihd.net/ugc/957483070088799009/F4BDE21346595AB9ACAD54A5C6DD5B365C563997/)

**Comment by TinySimon** [comment]
Fixed
