### ISSUE TITLE
This

### ISSUE THREAD

**Issue by VindoesCompooter** [FredyH/Perpheads-Issues#811]
[ERROR] gamemodes/perp/entities/entities/ent_chemical_table/cl_init.lua:82: attempt to index a nil value
  1. GetChemicalColor - gamemodes/perp/entities/entities/ent_chemical_table/cl_init.lua:82
   2. f - gamemodes/perp/gamemode/modules/attachmentsystem/cl_attachment.lua:69
    3. ThinkFunction - gamemodes/perp/gamemode/modules/attachmentsystem/cl_attachment.lua:8
     4. CSModelThink - gamemodes/perp/entities/entities/ent_attachment_base/cl_init.lua:95
      5. Think - gamemodes/perp/entities/entities/ent_attachment_base/shared.lua:15
       6. unknown - gamemodes/perp/entities/entities/ent_chemical_table/cl_init.lua:46

Happens every second.

**Comment by mage1123** [comment]
To add to this, I got a similar error when I opened someone's table UI and they were about to start distilling, as they were adding the ingredients, a bunch of "Smartphones" start to appear as the contents, and the % nexto the "Discard content" has ridiculously high numbers. So not to sure what is going on there.

**Comment by TinySimon** [comment]
Can't replicate, but I've put a fix in that should probably prevent this.
