### ISSUE TITLE
Insane FPS drops when placing Chemical Table

### ISSUE THREAD

**Issue by mage1123** [FredyH/Perpheads-Issues#812]
When you equip the chemical table and you want to place it, you get insane FPS drops. I'm assuming that this has something to do with the "ghost" tables that are rendered in places that are "valid" placement positions for the table. This only occurs while you have the chemical table SWEP in your hand, placing it down or switching to keys makes the "ghosts" dissappear and the fps fixes.

**Comment by TinySimon** [comment]
Fixed
