### ISSUE TITLE
Adding this ingredient would ruin your mixture.

### ISSUE THREAD

**Issue by Sorleee** [FredyH/Perpheads-Issues#813]
Occasionally, while I've been trying to add muriatic acid to meth at 50% I've been seeing this:

Adding this ingredient would ruin your mixture.

However then I just try again and I can add it perfectly fine, no change in percentage anything. Spooked me a few times because I hit 190 when relying on the temperature reduction you get from adding new materials.

**Comment by TinySimon** [comment]
How long is it at 50% for? It might just be a rounding issue on the display and is actually at 49.9%

**Comment by Sorleee** [comment]
Sounds about right, only really occurred when I was watching it and it'd just hit 50%.

**Comment by TinySimon** [comment]
Should be fixable by changing the rounder on the display so that it rounds down.

**Comment by TinySimon** [comment]
Fixed
