### ISSUE TITLE
White shirts glitch

### ISSUE THREAD

**Issue by orzel1244** [FredyH/Perpheads-Issues#815]
Hey, most of players have white shiny shirts in my game, I've tried to reinstall but it does nothing
autoexec.cfg - https://pastebin.com/raw/WBzXYSQD
arguments - -console -nojoy -high +r_hunkalloclightmaps 0
![20190225171309_1](https://user-images.githubusercontent.com/8932578/53831243-a6e88500-3f84-11e9-9694-622991c97d80.jpg)

**Comment by LaCreepis** [comment]
enable mat_bumpmap in your config, this is a client side problem

if that doesn't work please post the commands in unknownCmds.cfg, I don't exactly remember what the cause of this is again

**Comment by MangoEvo** [comment]
Try changing gmod_mcore_test to 0

**Comment by orzel1244** [comment]
mat_bumpmap Makes it work, but it may be caused by gmod_mcore_test to 0, as I was using mat_bumpmap for so long. I'll test it
