### ISSUE TITLE
Forum shoutbox is broken for phones

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#816]
This issue has been acknowledged by Ayjay ever since we upgraded to Xenforo 2.5 or whatever got rid of the forum ratings, still present and very annoying. Happens whenever you post about 2 or 3 messages.

This issue is both for Android (also on the newest Android One/Pie version) and iOS.
Google Chrome, Firefox and every other browser so far have this issue where you type something all the letters in the word copy themselves every time you write a new letter. Chrome also has this issue where it lags the crap out of your browser whenever you enter a letter.
https://www.youtube.com/watch?v=Wn-ZEWlJHZE
_Sadly my workaround "to use something else and not x Browser" doesn't work kek https://github.com/FredyH/Perpheads-Issues/issues/801_

**Comment by Exnem** [comment]
On PC it also seems to not refresh until you post a message, where it will continue to not refresh until another one is sent, I'm unsure if this is a PC issue, or a forum issue. But looking into it wouldn't hurt.
It also sometimes lags the shit out of my PC whenever I type in shoutbox. I also use my native browser on my android phone, and works perfectly fine.

**Comment by TinySimon** [comment]
Third party addon, not a huge amount we can do.
