### ISSUE TITLE
Dispatcher Menu

### ISSUE THREAD

**Issue by JaniceMcG** [FredyH/Perpheads-Issues#820]
Sometimes if you click on an officers location through the units tab it will send you to the big suburbs houses even though they aren't there.

https://i.gyazo.com/f9e0cbed34a81fda15a43d44cf567761.mp4

**Comment by LilChicken** [comment]
I’ve noticed this happens when the officer is driving can still locate either by spamming locate or locating vehicle as a temp fix lol

**Comment by TinySimon** [comment]
Fixed
