### ISSUE TITLE
People going invisible, police computer

### ISSUE THREAD

**Issue by Ardomaxi** [FredyH/Perpheads-Issues#821]
so, in brief, people go invisible, i can only see their heads, names and guns, cant access the police computer.
i believe the problem resides in the police computer, everytime i press F3 the game lags and freezes for a second, and the problem occurs usually after i press F3 to open the computer.

[ERROR] gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37: Tried to use a NULL
entity!
  1. SetMoveTy pe - [C]:-1
   2. Reattach - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37
    3. unknown - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:65

its a very annoying glitch, especially if it occurs and you cannot leave due to a RP sit you're in. (and if it later involves shooting)

**PHOTO**

https://steamcommunity.com/sharedfiles/filedetails/?id=1681075908

**Comment by Ardomaxi** [comment]
p.s the problem occurs after a while, and after being officer usually. not to mention the fact that FPS drop after a while of playing, and its probably related, due to my understanding something is getting "filled" and is slowing things down.

**Comment by Ardomaxi** [comment]
update, this also happened 

[ERROR] gamemodes/perp/entities/effects/shell_eject/init.lua:107: attempt to index field 'Entity' (a nil value)
  1. unknown - gamemodes/perp/entities/effects/shell_eject/init.lua:107

**Comment by mage1123** [comment]
I doubt it has anything to do with accessing the police computer, the reason it lags when you open it is because it has to load in all the models that are used as "pictures" of the people on the police computer and it has always been like that, at least for me.

**Comment by LTMaas** [comment]
This usually happens after a bit of time on-duty as an officer, this never happens as a civilian but only bonemerging script errors whilst a cop, grew a long time before maybe hours and hours, but when I'm 1-2 hours as cop I get these bonemerging errors and only way to fix it is to relog.

On the FPS matter, pretty sure it's cause of the police lights or something, everytime I'm a cop I usually get like limited fps or some shit i don't know why, but after a shootout I respawn and it feels like my fps is capped at 20-30, and then im wondering why, when I'm civ I have no troubles with either of these issues

**Comment by TinySimon** [comment]
Issue is more likely due to the client entity limit being hit. Not a huge amount that can be done about that easily.

**Comment by TinySimon** [comment]
Fixed
