### ISSUE TITLE
Error upon joining the server with chatbox

### ISSUE THREAD

**Issue by Clarkylad** [FredyH/Perpheads-Issues#826]
`[ERROR] gamemodes/perp/gamemode/modules/chatsystem/cl_chat.lua:449: attempt to index global 'ChatBox' (a nil value)
  1. func - gamemodes/perp/gamemode/modules/chatsystem/cl_chat.lua:449
   2. unknown - lua/includes/extensions/net.lua:32`

**Comment by TinySimon** [comment]
Fixed
