### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by madjemauricio** [FredyH/Perpheads-Issues#827]
Im not sure if this is a bug but its not realistic in my opinion and I've lost tons of money because of it. So all consists in whenever a bomb explodes in a building ,lets imagine regals for example, your chemical table will start burning. I was basing in regals 2 and a bomb in regals 4 exploded I think it was police with c2 or something like that, and my chemical table started burning when it was not even near I dont think this is realistic.

**Comment by madjemauricio** [comment]
https://www.youtube.com/watch?v=vVJGl-c2nLE for example

**Comment by TinySimon** [comment]
Fixed
