### ISSUE TITLE
Drugs weird bug

### ISSUE THREAD

**Issue by Daigestive** [FredyH/Perpheads-Issues#828]
I started growing 20 mins later I came back and my drugs were on 0% so I thought i left it on paused. 10 mins after that I came back and saw it was still on 0% but i did something and it started going up again to like 15%. So i thought it might not be my drugs so i picked them to try and pick up the planter box and it went from showing me 10% to flowering for some reason. https://www.youtube.com/watch?v=fHCx3QC-6gU&feature=youtu.be

**Comment by TinySimon** [comment]
Issue was only a one day bug
