### ISSUE TITLE
Voice Chat icon including normal/whisper text does not appear on the top left while drunk

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#829]
Easy to replicate.

I have a voice button that's toggled so I would speak to people without even realizing that I'm not talking.

**Comment by TinySimon** [comment]
Likely be impossible to solve without a fundamental redesign of onscreen effects. We're currently using the earliest possible render opportunity, for 2D effects: https://wiki.garrysmod.com/page/Render_Order
