### ISSUE TITLE
Minor bandage menu dialogue bug for Secret Service

### ISSUE THREAD

**Issue by Hendricks0610** [FredyH/Perpheads-Issues#830]
As soon as you speak to the NPC, instead of it usually asking you why you are in the PD as SS. It comes up with the dialogue of it giving you bandages, as seen in the screenshot below. When you click that you want bandages, the same text appears which is correct. It's just the opening dialogue needs to be fixed. 

https://steamuserimages-a.akamaihd.net/ugc/1010402472059229170/71F6938962FEAD225B89B8D85023FAB19EC98CAA/

**Comment by TinySimon** [comment]
Fixed
