### ISSUE TITLE
Trunk issue

### ISSUE THREAD

**Issue by Sorleee** [FredyH/Perpheads-Issues#832]
Been an issue for a while now where, when I have a gun in my trunk, it will not display any attachments and be completely inaccessible unless someone else gets it out for me.

Additionally, anything you put in the trunk after that will seemingly disappear and also be inaccessible unless someone else gets it out for me.

A LUA error pops up iirc, so I’ll try to reproduce it and get the error message. Seemingly a lot of people get it too but it might be client-side because it's often resolved by just rejoining.

**Comment by TinySimon** [comment]
It's a client side issue but we don't have a method to reproduce it so are unable to do much about it.
