### ISSUE TITLE
teleporting in shootout

### ISSUE THREAD

**Issue by Ysauzi** [FredyH/Perpheads-Issues#836]
had this problem 2 times now within like 1 week
in a shootout and i shoot people they just straight up teleport away from my sight

https://gyazo.com/88db3ea12fa0c408703e57969abca5ce

https://gyazo.com/ea2949bbdacd5d343937234d28363dbb

**Comment by LaCreepis** [comment]
Your lerp/net config settings might be screwed up

**Comment by TinySimon** [comment]
Is this still happening to you? I am unable to reproduce it.
