### ISSUE TITLE
Desk sergeant text

### ISSUE THREAD

**Issue by LilChicken** [FredyH/Perpheads-Issues#837]
When you go on duty the desk sergeant still says here is your firearm and that the mayor can set warrants.

**Comment by Exnem** [comment]
Please fix as soon as possible, it ruins my immersion, and is provision of false information by the desk operator, which is punishable by law, meaning the officer is lying when you sign up.

**Comment by LaCreepis** [comment]
**critical**

**Comment by TinySimon** [comment]
Fixed
