### ISSUE TITLE
Armoury no longer gives cops armour

### ISSUE THREAD

**Issue by LilChicken** [FredyH/Perpheads-Issues#839]
Not sure if this is on purpose but when I click resupply I no longer get added armour :(

**Comment by LilChicken** [comment]
Ok it does sometimes but only slightly? uh,

**Comment by Hendricks0610** [comment]
I have also had this problem however there is no known way to replicate the bug as of now and find out how and why it is happening - https://github.com/FredyH/Perpheads-Issues/issues/818

**Comment by TinySimon** [comment]
Closing as still no method of reproducing
