### ISSUE TITLE
MP7 does not seem to have have any armor penetrative capabilities

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#840]
Tested with XQ and Madda

Shot a MP7 on a LEO with moderately armored kevlar dead center, 1 shot, about 3~ meters away. Did not induce any bleed status even though it should be capable of penetrating the kevlar and cause bleeding.

**Comment by TinySimon** [comment]
Everything is currently working as intended. If you want to make a change to some of the gun damage settings, please make a suggestions post.
