### ISSUE TITLE
Randomly disconnected

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#844]
Console says that this is a Host Error
![g5THpfI](https://user-images.githubusercontent.com/14893257/56059314-16ac1580-5d64-11e9-9eb2-1f7845e44859.png)
Was just noclipping around and got randomly disconnected. My Garry's Mod is in 64-Bit but this has never happened before.

**Comment by TinySimon** [comment]
Probably 64 bit issue. Perhaps something related to clientside models?

**Comment by TinySimon** [comment]
Put in a fix, might work
