### ISSUE TITLE
Car kill logs kinda broken

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#845]
![7oF7ffI](https://user-images.githubusercontent.com/14893257/56098352-f0bb7800-5eff-11e9-813b-0c413524bbe3.png)

both people died at the same time, it only shows up as "prop_vehicle jeep" for smo (in-game logs showed up as driverless car). Would be hard to determine if only 1 person died and who the car belonged to if there are no vehicle logs of the person exiting their car or wrecking it.

**Comment by TinySimon** [comment]
Fixed
