### ISSUE TITLE
Fishing Rods can't fish, can't pick up

### ISSUE THREAD

**Issue by mik9900** [FredyH/Perpheads-Issues#847]
When you disconnect, the fishing rods will stay on the server for a small time before disappearing. If you reconnect after the fishing rods have disappeared, they will be sent to your storage and everything is great.

If you reconnect before they had time to disappear, the fishing rods will stay at the same place, they will stop catching fishes, you won't be able to pick them up Nor place more fishing rods.

**Comment by TinySimon** [comment]
Fixed
