### ISSUE TITLE
Planter box mL slider bug.

### ISSUE THREAD

**Issue by Bobikhere** [FredyH/Perpheads-Issues#848]
There is a bug where you cannot change the mL usage in the planter box by an even number of 0.1 some tend to only allow to change it by 0.2

For drug growers having the perfect mL like 2.1mL for weed or 2.5mL for coco is impossible which results in slower and uneven growing times (I have no idea if they produce less due to having too much or too less water but the grow times differ)

**Comment by TinySimon** [comment]
What resolution are you playing on?

**Comment by Bobikhere** [comment]
1920x1080

**Comment by TinySimon** [comment]
I can't reproduce this, it is working fine for me. What are your mouse sensitivty settings?

**Comment by Bobikhere** [comment]
Hmm, that's odd... Its very low with a very low dpi, I think 1.8 and 800dpi
