### ISSUE TITLE
Opening storage chest

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#849]
[ERROR] gamemodes/perp/gamemode/modules/itemsystem/sh_inventory_ents.lua:425: attempt to call method 'OnInventoryOpened' (a nil value)
  1. v - gamemodes/perp/gamemode/modules/itemsystem/sh_inventory_ents.lua:425
   2. func - gamemodes/perp/gamemode/modules/itemsystem/cl_inventories.lua:356
    3. unknown - lua/includes/extensions/net.lua:32

Got this error when opening the storage chest randomly.
Thought I'd report it as I don't entirely know what this means.

**Comment by TinySimon** [comment]
Fixed
