### ISSUE TITLE
PLPD - TFU C2 Respawn without NLR after getting shot dead.

### ISSUE THREAD

**Issue by MikeyDutch** [FredyH/Perpheads-Issues#850]
Today I witnessed a bug, how it happened.
We were planning a raid on GlassCo due to officers getting killed there. I picked up HVY TFU gear and went there when I arrived I took C2 and placed it on the garage door. when I was placing it (the load bar saying placing C2) I got shot dead when I dropped dead i pressed right click to detonate the C2 and then out of a sudden I was back respawned inside the PD without NLR timer. 

I contacted staff member Lelios1 and I tried it 3 times and 3 times I got respawned back to the PD. I could not get my shadowplay going so I restarted my PC to see if that worked but didnt. then I went back on duty again took HVY TFU Gear again and we tried it for the 4th time on the garage door at moron shippin co and also this time when the C2 was just placed and I died I right clicked and it again respawned me back to the PD alive and no NLR.

**Comment by Sorleee** [comment]
Same thing happened to me in the exact same circumstances just now, has happened to me before without  the use of C2 but it's very rare.

**Comment by nutrient10** [comment]
Happened to me again just now

**Comment by TinySimon** [comment]
Fixed
