### ISSUE TITLE
Bank robbery

### ISSUE THREAD

**Issue by LegendRF** [FredyH/Perpheads-Issues#853]
So today I robbed the bank with my friends killed cops didn't we hid in projex all was good then my friends received the drop place notification I didn't get it I thought it was nothing then they delivered the money and waited in projex, they received the money notification but I didn't  
 
lastly, I didn't leave the bank area the furthest was the hospital

**Comment by TinySimon** [comment]
The logs say you were removed from the robbery due to leaving the area before the vault was opened.

The fact that the logs say this means you must have received a notification, as the notification is triggered immediately before the log is sent.
