### ISSUE TITLE
Meth not always giving exact amounts

### ISSUE THREAD

**Issue by sm3312** [FredyH/Perpheads-Issues#854]
When I distil the ephedrine into the distilled water it doesn't always work exactly, sometimes I get 2L of ephedrine into the flask and a tiny amount in the distillery (like 0.01L.) Sometimes I get 0L left in the distillery and 1.991L in the flask. I'm not really sure why this happens, I'd have a screenshot but I blew up the table. Most the time it is fine though, 2L in the flask and 0L in the distillery.

**Comment by TinySimon** [comment]
Do you have any screenshs of this happening?

**Comment by sm3312** [comment]
No sorry, I would have taken some but I blew it up whilst speaking to an admin about it. I haven't played recently so I don't know if it's still happening.
