### ISSUE TITLE
Trunk bug

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#857]
[ERROR] gamemodes/perp/gamemode/modules/vehiclesystem/cl_vehicles.lua:172: attempt to call method 'OnInventoryOpened' (a nil value)
  1. v - gamemodes/perp/gamemode/modules/vehiclesystem/cl_vehicles.lua:172
   2. func - gamemodes/perp/gamemode/modules/itemsystem/cl_inventories.lua:356
    3. unknown - lua/includes/extensions/net.lua:32

**Comment by TinySimon** [comment]
Should be fixed now
