### ISSUE TITLE
Courier is broken

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#859]
You don't get any salary
![BtfaerO](https://user-images.githubusercontent.com/14893257/58374740-b05e0980-7f43-11e9-8d91-1eeb26de24f6.png)

I delivered a $43,000 package to a person but he picked it up without me having it put in my delivery SWEP first which means I didn't get any money for delivering his package. Have a replay of this happening if you really need it.

**Comment by TinySimon** [comment]
Appears to be an issue when people collect packages from the warehouse itself, or from the back of the van directly.

**Comment by TinySimon** [comment]
Fixed
