### ISSUE TITLE
Events and jobs

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#860]
You can sign up for any job about half a second before an event starts, meaning you can become a firefighter, medic, courier, SS, cop and even taxi driver with an AK or M4 in the raid events.

https://i.imgur.com/d7ZgGWs.jpg

**Comment by nutrient10** [comment]
I signed up for cop around a second before one of these events started, after the event ended instead of being demoted I was still a cop, however, I had my civilian clothes on.

**Comment by Exnem** [comment]
lul

**Comment by TinySimon** [comment]
Seems to be fixed now
