### ISSUE TITLE
Baseball bats on-duty

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#861]
Via the combination of some creative
+left
-left
+right
-right
+forward
-forward
+walk
-walk
+use
-use
commands in console you can use shop menus to purchase items, even illegal ones on-duty.
http://puu.sh/DxuoP/e9f16316e6.jpg

**Comment by LaCreepis** [comment]
bruh is this the Konami code equivelant of perp

**Comment by Exnem** [comment]
Yes you do this to spawn a baseball bat by pressing this key combination.

**Comment by TinySimon** [comment]
Related to #796

**Comment by Exnem** [comment]
But not the same. This one uses the actual store at a'blaze it.

**Comment by TinySimon** [comment]
Fixed
