### ISSUE TITLE
Revived instantly

### ISSUE THREAD

**Issue by LegendRF** [FredyH/Perpheads-Issues#865]
5 mins ago dylan punched me to death but i didnt die my gun was dropped but there wasnt a  black or red screen just a body from nowhere , my gun got dropped and my health went back to full   https://steamcommunity.com/sharedfiles/filedetails/?id=1755035849

**Comment by LegendRF** [comment]
https://plays.tv/video/5cee7061851020dffd/natsumi-cheater

**Comment by TinySimon** [comment]
Duplicate #850
