### ISSUE TITLE
OFFICE WINDOWS

### ISSUE THREAD

**Issue by SC3-Gazzy-Gaming** [FredyH/Perpheads-Issues#871]
OFFICE WINDOWS CAN ONLY BE SHOT THROUGH WITH A RIFLE, A PISTOL OR SMG Can't shoot through it, kind of stupid.

**Comment by LaCreepis** [comment]
depends on the angle https://github.com/FredyH/Perpheads-Issues/issues/535

**Comment by TinySimon** [comment]
@LaCreepis Partially correct. The pistol rounds aren't actually able to go through due to the thickness of the glass. However, the correct way to fix this would actually increase how much damage rifles do through it too.

**Comment by TinySimon** [comment]
Fixed in v5
