### ISSUE TITLE
SS (sometimes) doesn't get demoted

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#873]
When the mayor got assassinated today, I was notified that I was demoted from Secret Service, however, I still had the job.

I'm not 100% sure how to replicate this but I was in the back of a police cruiser when I was "demoted", maybe this may help replicate it.

**Comment by nutrient10** [comment]
It seems to have happened again
https://i.imgur.com/tlzE3kU.jpg

**Comment by TinySimon** [comment]
Fixed
