### ISSUE TITLE
Police Database Blank Search

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#874]
[ERROR] gamemodes/perp/gamemode/modules/policedatabase/gui/search.lua:122: bad argument #1 to 'WriteUInt' (number expected, got nil)
  1. WriteUInt - [C]:-1
   2. DoClick - gamemodes/perp/gamemode/modules/policedatabase/gui/search.lua:122
    3. unknown - lua/vgui/dlabel.lua:234

Warning! A net message (perpheads_police_db_property_lookup) is already started! Discarding in favor of the new message! (perpheads_cheat_check)

This happens when I click search without selecting a property in the police database in a vehicle. Not sure if it's the same in a chair in the PD.

**Comment by TinySimon** [comment]
Fixed
