### ISSUE TITLE
Bobby pins/crowbars

### ISSUE THREAD

**Issue by Sorleee** [FredyH/Perpheads-Issues#876]
You can  pick up bobby pins/crowbars whilst on duty as any job to surpass the Equipment limit as a Civilian. I'd imagine this will work for anything else that you don't keep on you when you go on duty, such as magazines and bandages.

https://i.imgur.com/fUyOSRL.jpg

**Comment by SamuelSheppard** [comment]
Not much to be done here really, it's either this way or deleting items.
