### ISSUE TITLE
TFU and Flashbangs

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#877]
This is how I had this happen to me.
I signed up as officer
Geared light
Equipped Flashbang
Geared heavy
Equipped Flashbang
Geared down to light
Geared down to officer

I have no idea if that is what exactly caused the issue, but I managed to get a flashbang as an officer, and it wasn't an item in my inventory.
http://puu.sh/DG7Yh/9bc91dff3c.jpg
and
https://www.youtube.com/watch?v=-nCi0bxpxBE&feature=youtu.be

**Comment by nutrient10** [comment]
I was just about to make a bug report on this myself.
If you equip a flashbang or C2 in light or heavy gear, then change to the opposite type of gear, you essentially get a free flashbang or C2 and you can keep it when you go out of gear.

**Comment by TinySimon** [comment]
Fixed
