### ISSUE TITLE
MP7 40 round mag

### ISSUE THREAD

**Issue by LoganFinch** [FredyH/Perpheads-Issues#880]
After crafting 5 every time I came to put in the fully loaded 40 round mag it seemed I had to reload it twice for the mag to actually enter the gun?

**Comment by TinySimon** [comment]
I can't reproduce this currently, however I have another bug fix that isn't live yet. Let me know if this is still an issue tomorrow.

**Comment by LoganFinch** [comment]
https://youtu.be/3zsKV1xCn30

**Comment by TinySimon** [comment]
Fixed
