### ISSUE TITLE
Unable to reload the MP9 with a extended mag

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#881]
Not able to reload the MP9 when it has a extended mag loaded in and you want to put a fresh one in, loads it with 0 bullets and doesn't put the magazine from your inventory into the gun.
Haven't tested yet with MP7.

**Comment by TinySimon** [comment]
I can't reproduce this currently, however I have another bug fix that isn't live yet. Let me know if this is still an issue tomorrow.

**Comment by Sorleee** [comment]
Seems to be fixed for me, haven't tested after unloading the mag but normal reloading seems fine.

Once I've tried using it, I'll include what happens with an unloaded mag.

**Comment by LaCreepis** [comment]
Works now
