### ISSUE TITLE
Equipping multiple things at once in the same slot

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#882]
You can equip multiple things at once by clicking on one thing, then quickly another in the inventory the way it works right now. Sometimes this leads to equipping bugging out and you freezing in place with an unknown way of getting out of said situation, im pretty sure someone pushing you fixes it, but that's unknown. Whatever would naturally break an equip should be it.

**Comment by TinySimon** [comment]
Fixed

**Comment by Exnem** [comment]
This is semi-fixed, I can still equip C2 and battering ram at the same time with enough effort, I don't really have much of an idea on how it happens, this requires further testing.

**Comment by TinySimon** [comment]
Do you have a video of you doing it?

**Comment by Exnem** [comment]
i'll try getting one sometime next week, i'm moving today-tomorrow and won't have internet until monday or tuesday

**Comment by Exnem** [comment]
This appears to be fixed
