### ISSUE TITLE
A distinct lack of police sirens

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#883]
Appears that police sirens don't exist.
Either the sound file(s) is/are missing, or a bug has occurred that disallows for Q to trigger the siren, or is playing the wrong sound.

Here's how you reproduce this issue: Spam Q like a monkey on crack.
Here's what happens: Nothing
Here's what I expect to happen: My ears being raped by a siren.
https://www.youtube.com/watch?v=X_PLsiVl164&feature=youtu.be

**Comment by TinySimon** [comment]
It will be fixed on a map restart
