### ISSUE TITLE
Disable siren lights when driving in first person

### ISSUE THREAD

**Issue by LaCreepis** [FredyH/Perpheads-Issues#885]
Probably tricky to find a fix for it. I've been driving in first person for a while and whenever I put on my siren lights it's not a pleasant ride due to how everything lights up in different colors literally giving me a seizure. If possible, it would be nice if the vehicle we're driving does not render the lights (or does not affect the lighting of the car) when in first person but we should still be able to see the other one's.
Also, when driving up slopes (e.g. highway on-ramp) the camera tilts in a weird way.

If it's hard don't bother. Might be engine related in the first place.

**Comment by TinySimon** [comment]
This has been an issue for ages, but previously only during the night. Another bug made it happen 24/7.

I have fixed both and reduced the brightness of your lights while you are in first person.
