### ISSUE TITLE
Bonemerging script error.

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#886]
CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/entities/entities/ent_attachment_base/cl_init.lua:81: Tried to use a NULL entity!
  1. SetMoveType - [C]:-1
   2. CSModelThink - gamemodes/perp/entities/entities/ent_attachment_base/cl_init.lua:81
    3. Think - gamemodes/perp/entities/entities/ent_attachment_base/shared.lua:15
     4. unknown - gamemodes/perp/entities/entities/ent_chemical_table/cl_init.lua:46

CBaseEntityList::AddNonNetworkableEntity: no free slots!

[ERROR] gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37: Tried to use a NULL entity!
  1. SetMoveType - [C]:-1
   2. Reattach - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:37
    3. func - gamemodes/perp/gamemode/modules/bonemerging/cl_bonemerging.lua:54
     4. unknown - lua/includes/extensions/net.lua:32

**Comment by Exnem** [comment]
I'm on chromium beta

**Comment by TinySimon** [comment]
Fixed, probably
