### ISSUE TITLE
Smooth Metallic Paint, Again.

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#887]
tiny you closed this last time, but seriously look at this, Mac had the same issue.

Here's mac's smooth metallic [https://imgur.com/a/cENDwel#BkPC71g](url)

Here's what my S2K should look like [https://i.imgur.com/ByGCazC.png](url)

And here's what it does [https://i.imgur.com/IHybGTH.jpg](url)

For comparison, here's my pearlescent Audi RS4 Avant, which has a similarly metallic sheen, in the dark.
[https://i.imgur.com/iDgTaWe.jpg](url)

And here it is in the light. [https://i.imgur.com/mEgiB4b.jpg](url)

Here's my S2K in the same spot [https://i.imgur.com/SlGTBwB.jpg](url)

If this is just lighting differences i'm more than just colourblind.

**Comment by LaCreepis** [comment]
Duplicate
https://github.com/FredyH/Perpheads-Issues/issues/678
