### ISSUE TITLE
TFU gear not working correctly?

### ISSUE THREAD

**Issue by LoganFinch** [FredyH/Perpheads-Issues#889]
The video starts with me in heavy gear, I come to put on light gear, then I only have access to light guns while I look like I'm in heavy gear with also the status "heavily armored" also I do not believe rearming resets this to the armor it should be at

https://www.youtube.com/watch?v=Qup4n7GZHEE&feature=youtu.be

**Comment by LoganFinch** [comment]
Can't seem to get it to happen anymore?

**Comment by Exnem** [comment]
This happens randomly, sometimes when you just sign up, go light then heavy, other times it's after a shootout or taking damage, other times it happens when I jump out a vehicle. It's random as I'm unable to find the exact source to this issue.

**Comment by SamuelSheppard** [comment]
Fixed. Issue was in code for removing TFU equipment
