### ISSUE TITLE
Some items glitch fishing rods

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#891]
When catching certain items, mostly plastic crates, the props can collide with the hook and cause the rod to go flying as it's tugged along by the hook. Perhaps a fix for this could be to just make the caught items no-collided with the hook? I've seen it happen with plastic crates, fish, kitty litter, and garbage bags, and breenbusts to name a few.

**Comment by TinySimon** [comment]
Do you have a video or picture of this happening?

**Comment by PuffySandvich** [comment]
No, but I know other people have had it happen as well. Every once in a while someone's fishing rod will go flying off.

**Comment by PuffySandvich** [comment]
@TinySimon 
https://youtu.be/Ky3dhtJPuOg

**Comment by TinySimon** [comment]
Fixed
