### ISSUE TITLE
Increase Shotgun armour penetration

### ISSUE THREAD

**Issue by Daigestive** [FredyH/Perpheads-Issues#892]
https://i.imgur.com/SaoaxIk.gifv
Hello?

**Comment by TinySimon** [comment]
Please provide some more information such as the .dem file or other occurances, or this will be closed.

**Comment by Daigestive** [comment]
Spectate people with shotguns. IDK how you can be fine with civs getting 1 tapped from mid range yet a cop can survive getting headshotted from that range. It's a joke really.
