### ISSUE TITLE
No ammo in events

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#894]
In gun game and office raid today, in both events I spawned with no mag in my gun, and the spare mags I had were all empty but I still had access to physgun, fists and keys in gungame (so I just punched people to death instead).

I'm not too sure how to replicate this, the only thing that comes to mind is shortly before the events started I used the gun range and clicked I want to use my own ammo.

**Comment by TinySimon** [comment]
I think I know what caused this, which was actually fixed in the last update. Let me know if it's still an issue.
