### ISSUE TITLE
DNA Scanner Error

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#895]
[ERROR] gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:184: attempt to index local 'DNA' (a nil value)
  1. setupDNA - gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:184
   2. SetData - gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:249
    3. ShowDNAAnalyzer - gamemodes/perp/entities/weapons/weapon_perp_dnasampletool/shared.lua:47
     4. func - gamemodes/perp/entities/weapons/weapon_perp_dnasampletool/shared.lua:71
      5. unknown - lua/includes/extensions/net.lua:32

Weapon used also says "Label"
I'm assuming this is when there is no weapon used (i.e. fists)

**Comment by nutrient10** [comment]
UPDATE:
Weapons don't seem to show, nor does the image of the person that attacked them
[https://i.imgur.com/Dk7PX4l.png](url)

**Comment by TinySimon** [comment]
Fixed
