### ISSUE TITLE
Honda S2K license plate

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#896]
![PrMGIJQ](https://user-images.githubusercontent.com/19747875/60555874-c01ff900-9d0c-11e9-89cf-cc4eb6480eee.jpg)

**Comment by TinySimon** [comment]
This is an issue with the body kit. It will require more work than I thought to have a flexible one.

**Comment by TinySimon** [comment]
Fixed, and many others too
