### ISSUE TITLE
DEMOS

### ISSUE THREAD

**Issue by SkidMark69** [FredyH/Perpheads-Issues#900]
my SHIFT-F2 doesnt bring up my demos and i cant find the key bind what do i do?

**Comment by nutrient10** [comment]
The latest gmod update stops you from using the Shift+F2 feature when not in a demo. Are you sure you were already in a playing demo when you tried to do this?

**Comment by SkidMark69** [comment]
That might have been the problem. But how can I view and edit these demos?

**Comment by SkidMark69** [comment]
I have just tried to shift f2 in a demo and nothing happened

**Comment by TinySimon** [comment]
It looks like the update GMod update that @nutrient10 refers to has a few bugs in it, nothing related to our code.

However, once you've opened a demo through the menu or using the `playdemo` command, you can open the UI through the `demoui` or `demoui2` commands, if SHIFT+F2 isn't working.
