### ISSUE TITLE
Can't pick up firework from Fishing Rod

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#901]
[https://i.imgur.com/yFUg2pi.jpg](https://i.imgur.com/yFUg2pi.jpg)

I'm spamming E in this photo, i've tried spamming AROUND it too, nothing

**Comment by TinySimon** [comment]
Fixed a minor cause of this. It will still happen in this example because of the wooden board messing with the use function in the engine.
