### ISSUE TITLE
Can't get a custom plate

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#903]
Whenever I try to get a custom plate I get the following script error and I see the following image. I also can't get out of the NPC GUI menu as it has no options for me to click on and I have to rejoin.
[ERROR] gamemodes/perp/gamemode/modules/vehiclesystem/licenseplates/cl_licenseplates.lua:54: bad argument #1 to 'pairs' (table expected, got userdata)
  1. pairs - [C]:-1
   2. UpdateEntiyRegistration - gamemodes/perp/gamemode/modules/vehiclesystem/licenseplates/cl_licenseplates.lua:54
    3. Init - gamemodes/perp/gamemode/modules/vehiclesystem/gui/licenseplates_custom.lua:24
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
      5. ShowCustomPlatePanel - gamemodes/perp/gamemode/modules/vehiclesystem/licenseplates/cl_licenseplates.lua:201
       6. DoAction - gamemodes/perp/gamemode/modules/jobs/mayor/npc_countyclerk.lua:133
        7. DoClick - gamemodes/perp/gamemode/modules/npcs/cl_dialog.lua:113
         8. unknown - lua/vgui/dlabel.lua:234
[https://i.imgur.com/ZyShoLI.png](https://i.imgur.com/ZyShoLI.png)

**Comment by TinySimon** [comment]
Fixed
