### ISSUE TITLE
DNA Scanner Error

### ISSUE THREAD

**Issue by JaniceMcG** [FredyH/Perpheads-Issues#904]
A roadcrew worker had run a civilian over and while taking DNA it broke completely and it showed the killer as "Label"

[ERROR] gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:119: attempt to call method 'IsGovernmentOfficial' (a nil value)
  1. processDNA - gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:119
   2. unknown - gamemodes/perp/gamemode/modules/jobs/medic/cl_dnasampler.lua:171

**Comment by TinySimon** [comment]
Fixed
