### ISSUE TITLE
Since the first person light fix, lights now sometimes disappear entirely

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#909]
https://i.imgur.com/kr9Xw1j.jpg

This also happens with police cars, and it tends to be all at once. this is very annoying when the lights are being used in a shootout to increase visibility, and also makes RC lights less effective

**Comment by ModoSN** [comment]
explain the issue?

**Comment by PuffySandvich** [comment]
> explain the issue?

click the image, you'll see exactly what the issue is. The lights aren't there, despite being on.

**Comment by TinySimon** [comment]
Closing due to lack of information on what the issue is, or how to reproduce it
