### ISSUE TITLE
radio volume

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#915]
Radio volume doesn't change until you rejoin the server

**Comment by ModoSN** [comment]
Stop spamming stupid issues...

**Comment by PuffySandvich** [comment]
> Stop spamming stupid issues...

god forbid I report bugs in the bug reporting area so they can be fixed.

**Comment by PuffySandvich** [comment]
spaceshots told me that if you turn the radio off and on again it'll update the volume. if that's true then this should be tagged as minor

**Comment by TinySimon** [comment]
Fixed
