### ISSUE TITLE
Can't stack items in trunk properly

### ISSUE THREAD

**Issue by PuffySandvich** [FredyH/Perpheads-Issues#917]
Can't stack items in trunk properly. When you drag an item on top of more of the same item, ex, dragging Cod onto Cod, it'll say the slot is already occupied, even if it's the same item with plenty of room left in the trunk. This means you have to put items in 5 at a time by right clicking rather than doing a one time transfer, which triples the time taken to perform the task.

**Comment by TinySimon** [comment]
Duplicate #795
