### ISSUE TITLE
Toyota Supra makes no noise

### ISSUE THREAD

**Issue by CGreenwood96** [FredyH/Perpheads-Issues#921]
The engine of the Toyota Supra doesn't make any noise when driving.

https://youtu.be/gT-zG4IRF0c

**Comment by Aero56** [comment]
This is a common bug in TDM, every car has this. When you press W the sound bugs out and you hear nothing. Try to press W again to reset the sound

**Comment by nutrient10** [comment]
> This is a common bug in TDM, every car has this. When you press W sometimes the sound bugs out and you hear nothing. Try to press W again to reset the sound

It isn't this, there has been a bug where some engine sounds don't work, it should have been fixed though. Maybe reinstall the content @CGreenwood96 and see if that helps.

**Comment by CGreenwood96** [comment]
It's seems to have been fixed m

**Comment by TinySimon** [comment]
This was fixed
