### ISSUE TITLE
Unlocked cars releasing handbrakes when failing to get into it

### ISSUE THREAD

**Issue by StWylde** [FredyH/Perpheads-Issues#923]
https://plays.tv/video/5d2f555b14b45f7028/bug-with-swatvan

Pressing E on the SWAT Van with any role, be it cop, civilian, etc. Disables the handbreak and causes it to roll if on a hill. There is potential for abuse here, such as if the SWAT Van is being used as part of a road block, it can be disabled with E and pushed out the way.

**Comment by Aero56** [comment]
This happens with every car when its unlocked

**Comment by PuffySandvich** [comment]
> This happens with every car when its unlocked

It doesn't need to be unlocked as far as I can tell. It's happened to me when my car was off and locked before as well.

**Comment by TinySimon** [comment]
Fixed
