### ISSUE TITLE
Leaving Orgs

### ISSUE THREAD

**Issue by YaboiSpooky** [FredyH/Perpheads-Issues#924]
I am trying to leave my current org as it is dead, my problem is that the discription has grown to be over the leave button, and it's prioritized itself so i cant leave my org, the higher up is offline for quite a while so i feel stuck in this situation now.

**Comment by nutrient10** [comment]
What resolution are you playing at?

**Comment by Aero56** [comment]
change ur res to something else and try

**Comment by LoganFinch** [comment]
Bugs tend to occur a lot if you cheat, its like a passive karma.

**Comment by TinySimon** [comment]
Hard to fix without know which resolution this is an issue at...
