### ISSUE TITLE
distilling drug report

### ISSUE THREAD

**Issue by tinymod** [FredyH/Perpheads-Issues#929]
https://www.youtube.com/watch?v=2whVQ2dZE4Q&feature=youtu.be

**Comment by TinySimon** [comment]
What am I looking at?

**Comment by PuffySandvich** [comment]
AFAIK that's the residual heat as it cools off allowing the drugs to distill. The flame doesn't need to be there for it to happen, it just needs to be hot enough. Seems like it's working as intended.
