### ISSUE TITLE
Invincibility

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#931]
- Have a staff member physguns you as a paramedic, do any gmod act
- zombie
- dance
- forward
- halt
- group
- beckon
- etc
- wait for the animation to finish
- in addition it unfreezes your character in their grip allowing you to look around
- staff member puts you down bugs your character, you're invincible/immune to any damage except fire but you cannot use your keys, get in any open vehicles or use any of your items, and you cannot pick up items or props.
- In addition you can resign as medic and still be immune, and in theory you can also sign up as any job and also still be immune, i believe, this is untested.

- On top of this you can unfreeze yourself by using a gmod act if a staff member freezes you with their god stick and your physgun is removed when you sign up.
- This is very flawed and can easily be abused by some paki 9 year old who suddenly does an act as a medic.

**Comment by TinySimon** [comment]
Fixed
