### ISSUE TITLE
Mayor can equip bobby pins and raid

### ISSUE THREAD

**Issue by Samsterminator** [FredyH/Perpheads-Issues#939]
Mayor can equip bobby pins and raid

**Comment by Samsterminator** [comment]
It actually seems that all government officials can do this by buying or picking up dropped bobby pins, and I believe a few days ago a police officer used a picked up bobby pin to raid someones bazaar shop.

**Comment by jimmythehamster** [comment]
not a bug, a feature !

**Comment by SamuelSheppard** [comment]
Bobby Pins are not illegal so there is nothing stopping any gov job from picking it up. How they use the item is up to them, if the mayor breaks the law, report him.

Not a bug.
