### ISSUE TITLE
Sofas

### ISSUE THREAD

**Issue by TheHitMan1** [FredyH/Perpheads-Issues#946]
Once sat on them you can't get off them, Staff has to remove it or TP you.
https://youtu.be/cXjhaedJXZY

**Comment by AyjayMartin** [comment]
Can't seem to replicate this, is there anything specific you do to get this to happen or does it appear to be random?

**Comment by TheHitMan1** [comment]
It was my own Sofa, it was frozen at first when I got on it, so could be when it's frozen?
