### ISSUE TITLE
equipping greande

### ISSUE THREAD

**Issue by orzel1244** [FredyH/Perpheads-Issues#950]
I've been hiding by barricades, wanted to equip nade, then my character stand up, and I got shoted right in my head, what the fuck? why would anyone need to stand up while equipping greande?

**Comment by SamuelSheppard** [comment]
This happens as we are freezing the player when they equip a weapon/item. Not really a bug as it works as intended, but definitely worth looking into.

**Comment by Exnem** [comment]
Just make your character super slow like when you refill magazines, you're still able to move around. That might actually be bandaging or something, either way you know what I mean.

**Comment by TinySimon** [comment]
Done
