### ISSUE TITLE
Lua errors in console

### ISSUE THREAD

**Issue by Zexinity** [FredyH/Perpheads-Issues#952]
[ERROR] gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76: Tried to use a NULL entity!
  1. SetPlaybackRate - [C]:-1
   2. unknown - gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76

[ERROR] gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76: Tried to use a NULL entity!
  1. SetPlaybackRate - [C]:-1
   2. unknown - gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76

[ERROR] gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76: Tried to use a NULL entity!
  1. SetPlaybackRate - [C]:-1
   2. unknown - gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76

[ERROR] gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76: Tried to use a NULL entity!
  1. SetPlaybackRate - [C]:-1
   2. unknown - gamemodes/perp/entities/weapons/roleplay_keys/shared.lua:76

**Comment by TinySimon** [comment]
What did you do to make this happen?
