### ISSUE TITLE
Major Car Downgrade Bug

### ISSUE THREAD

**Issue by A1LARSEN** [FredyH/Perpheads-Issues#954]
Simple as, video shows that I attempted to downgrade my vehicle, I pressed no by accident and I check my bank account to make sure I got the money, which I realised oh I pressed no by accident, then I pressed yes and I thought I was loosing my mind so I attempted to upgrade my vehicle, thinking that it had a confirmation button too, nope I was wrong and I accidentally upgraded my car and wasted some fucking money.

https://www.youtube.com/watch?v=Xfg8fVji5aI

**Comment by nutrient10** [comment]
Happened to Sabre last night, exact same thing except he surprisingly has enough brain cells not to buy another upgrade

**Comment by SamuelSheppard** [comment]
Been fixed for a while.

Was issue only on client side.
