### ISSUE TITLE
Nades not damaging cars.

### ISSUE THREAD

**Issue by DaftPunk1234** [FredyH/Perpheads-Issues#960]
Weird thing i experienced, 8 nades thrown at cars, not damaged. 6 thrown at a bugatti, and another 2 thrown at one of super's cars to test why it wasnt.

**Comment by LaCreepis** [comment]
a demo would be nice

**Comment by Madda2000** [comment]
Was the engine on?

**Comment by DaftPunk1234** [comment]
negative, just found out that you need to have the engine on for it to be damaged.....
