### ISSUE TITLE
Allowing the AK-101 to take the rifle flashlight in the range causes an issue

### ISSUE THREAD

**Issue by StWylde** [FredyH/Perpheads-Issues#963]
Go to the shooting range, then click rifles, then go to the AK-101. Click the rifle flashlight attachment and suddenly, whenever you have the gun in passive, your vision is obstructed with a flying rifle sight. Nothing major and would be a quick fix, but overall you should probably look into it.

**Comment by TinySimon** [comment]
Fixed
