### ISSUE TITLE
TFU barely get flashed

### ISSUE THREAD

**Issue by ashurxd** [FredyH/Perpheads-Issues#964]
As TFU, when being flashed as crims, I sometimes barely get blinded at all, even by Lelios (When he was cop we tried) I got flashed, and got white, but I could still see the playermodels, I think it could just be a me issue (I have max brightness), but yeah i think its an issue, it's happened to me since i;'ve been tfu, and others had this issue too

**Comment by LaCreepis** [comment]
It's a function, back when SWAT was still about with helmets and visors that would reduce their effectiveness.
