### ISSUE TITLE
Can't place chests in suburbs lakehouse 5

### ISSUE THREAD

**Issue by Sorleee** [FredyH/Perpheads-Issues#967]
TItle - owned it and couldn't place a chest in there, could place a chest in suburbs lakehouse 4 yesterday though when I bought that.

**Comment by Sorleee** [comment]
Pretty sure this applies to the majority of the lakehouses, also doesn't work in lakehouse 1

**Comment by nutrient10** [comment]
This seems to be a problem in a lot of places I.e. large shop 3 I believe it was

**Comment by Sorleee** [comment]
seem to be unable to place them anywhere now
