### ISSUE TITLE
PD Armoury to spawn vehicle

### ISSUE THREAD

**Issue by LTMaas** [FredyH/Perpheads-Issues#971]
Just tried to spawn my vehicle via the Armoury and lua error occured and now im stuck like a motherfucker.

[ERROR] gamemodes/perp/gamemode/modules/npcs/cl_dialog.lua:113: attempt to call upvalue 'DoAction' (a nil value)
  1. DoClick - gamemodes/perp/gamemode/modules/npcs/cl_dialog.lua:113
   2. unknown - lua/vgui/dlabel.lua:234

https://steamuserimages-a.akamaihd.net/ugc/778490115599213776/50A0AD2406F9E17A7E8A3C573120617EC7E9EB50/

**Comment by nutrient10** [comment]
Please add a "<Leave>" button as well!

**Comment by AyjayMartin** [comment]
This will be fixed on restart.
