### ISSUE TITLE
Penguin 2019 Doll bugs and issues

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#976]
When dropped it has no physics and cannot be picked up again.
I assume it returns to storage on DC.

On top of that, here's an error I received immediately on join.

[ERROR] gamemodes/perp/entities/weapons/item_holiday2019doll/shared.lua:43: Tried to use a NULL entity!
  1. SetColor - [C]:-1
   2. unknown - gamemodes/perp/entities/weapons/item_holiday2019doll/shared.lua:43

The penguin npc is inside an invisible wall, if you get out of your car near it or in it you will not be able to move

**Comment by AyjayMartin** [comment]
This should be fixed already, make another bug report if you find any further problems.
