### ISSUE TITLE
Childlock

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#977]
You're able to steal police cars.
Childlock must be enabled.

first case of this happening
https://www.youtube.com/watch?v=L_0zjmJW568&feature=youtu.be

second case as demonstration
https://www.youtube.com/watch?v=k88tbc9gCBc&feature=youtu.be

**Comment by nutrient10** [comment]
Fixed

**Comment by Exnem** [comment]
Not as of post date, now it is.
