### ISSUE TITLE
Bobby pinning

### ISSUE THREAD

**Issue by Exnem** [FredyH/Perpheads-Issues#982]
https://www.youtube.com/watch?v=LW9q0Tlzn3Q&feature=youtu.be

Bobby pinning for some reason doesn't allow you to pull out a gun, even after the animation completes.

**Comment by Madda2000** [comment]
Did this happen multiple times? Did you do anything specific to make it happen? I can't seem to reproduce this.

**Comment by Exnem** [comment]
Using the momentum I had, I think I started bobby pinning while still walking backwards, making me out of reach of the door in bobby pin terms, which is probably how that happened. That's the only thing I can think of.

**Comment by Synatec** [comment]
I get this a lot, the fix for me is switching to fists or keys and then to the gun. Maybe this helps? It obviously has something to do with animations as I also rarely get it after doing an emote.

**Comment by SamuelSheppard** [comment]
Should be fixed now.

Issue only occurred when someone opened the door at the same time.
