### ISSUE TITLE
Armoury NPC - Invalid guns object after respawning

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#983]
https://i.imgur.com/TEVrOZ6.jpg

```
[ERROR] gamemodes/perp/gamemode/modules/armory/gui/armory_button.lua:16: attempt to index field 'Item' (a nil value)
  1. SetItem - gamemodes/perp/gamemode/modules/armory/gui/armory_button.lua:16
   2. SetWeaponType - gamemodes/perp/gamemode/modules/armory/gui/amory_menu_weapon.lua:10
    3. Init - gamemodes/perp/gamemode/modules/armory/gui/armory.lua:35
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
      5. DoAction - gamemodes/perp/gamemode/modules/armory/npc_armory.lua:63
       6. DoClick - gamemodes/perp/gamemode/modules/npcs/cl_dialog.lua:113
        7. unknown - lua/vgui/dlabel.lua:234
```

**Comment by nutrient10** [comment]
I'm not 100% sure how to recreate this, however, I believe it always happened after I had died

**Comment by blobvis20** [comment]
[ERROR] gamemodes/perp/gamemode/modules/armory/gui/armory_button.lua:16: attempt to index field 'Item' (a nil value)
  1. SetItem - gamemodes/perp/gamemode/modules/armory/gui/armory_button.lua:16
   2. SetWeaponType - gamemodes/perp/gamemode/modules/armory/gui/amory_menu_weapon.lua:10
    3. Init - gamemodes/perp/gamemode/modules/armory/gui/armory.lua:29
     4. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:37
      5. DoAction - gamemodes/perp/gamemode/modules/armory/npc_armory.lua:63
       6. DoClick - gamemodes/perp/gamemode/modules/npcs/cl_dialog.lua:113
        7. unknown - lua/vgui/dlabel.lua:234
