### ISSUE TITLE
Report being too long

### ISSUE THREAD

**Issue by VindoesCompooter** [FredyH/Perpheads-Issues#988]
I've learned that if you submit a reply to a report that is way too long, it'll dogbollock the report and it can't be opened, returning this error:

[ERROR] gamemodes/perp/gamemode/modules/guicore/general/dtextarea.lua:65: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. Split - gamemodes/perp/gamemode/modules/guicore/general/dtextarea.lua:65
    3. SetText - gamemodes/perp/gamemode/modules/guicore/general/dtextarea.lua:398
     4. SetMessage - gamemodes/perp/gamemode/modules/scam/gui/reports.lua:20
      5. AddReply - gamemodes/perp/gamemode/modules/scam/gui/reports.lua:188
       6. SetReport - gamemodes/perp/gamemode/modules/scam/gui/reports.lua:182
        7. OnClickLine - gamemodes/perp/gamemode/modules/scam/gui/reports.lua:390
         8. unknown - lua/vgui/dlistview_line.lua:81

**Comment by Madda2000** [comment]
How do you even manage this? Did you write a bible? Anyways set character limit to 25000
