### ISSUE TITLE
Player clip inside Parker Tunnel?

### ISSUE THREAD

**Issue by nutrient10** [FredyH/Perpheads-Issues#991]
https://i.imgur.com/xqZHkCE.jpg

https://i.imgur.com/0cDYpO9.jpg

Pretty self-explanatory from the above images, got a report about someone getting out of their car and being stuck in a player clip and found the red area to be the outline of it, the player clip looks a bit like the shape of a square, honestly have no idea how this has occurred so thought I'd report it.

**Comment by Madda2000** [comment]
Old issue with V2, most likely a misplaced playerclip. Won't be an issue after mapswitch.

**Comment by nutrient10** [comment]
Oh lol, I had no idea of this until just now
