### ISSUE TITLE
Stacking tickets on the same person

### ISSUE THREAD

**Issue by Collier9** [FredyH/Perpheads-Issues#997]
The jailer NPC allows you to ticket people with outstanding tickets.

As long as multiple Officers have the ticket window open at the same time, tickets will go through. Thus, multiple tickets can be issued to one person.

**Comment by SamuelSheppard** [comment]
The being able to give someone a ticket when they already have one is per design.

The second part is not.

**Comment by SamuelSheppard** [comment]
Fixed
