### ISSUE TITLE
Fix RTU BMW Trunk

### ISSUE THREAD

**Issue by HaydenPERP** [FredyH/Perpheads-Issues#998]
Currently, the trunk of the marked RTU BMW only has 3 slots whereas the unmarked one has 5 slots. It's really annoying because when you go to store your shotgun, you have to remove the barricades.

**Comment by SamuelSheppard** [comment]
@HaydenPERP what BMW is this?

**Comment by HaydenPERP** [comment]
> @HaydenPERP what BMW is this?

The marked regular RTU BMW, I have no idea what model it is.

**Comment by SamuelSheppard** [comment]
Not a bug

**Comment by HaydenPERP** [comment]
@SamuelSheppard Can this bug please be fixed then: https://streamable.com/dtlks1
